CREATE FOREIGN TABLE CLIENTS_ARCHIVE
(
  ID SERIAL,
  NAME VARCHAR(35) NOT NULL,
  PHONE VARCHAR(15),
  EMAIL VARCHAR(50),
  IDCARDSCAN VARCHAR(100),
  NATIONALITY_ID INTEGER NOT NULL,
  HOMEADDRESS_ID INTEGER,
) SERVER archivesrv OPTIONS ( table_name 'clients', use_remote_estimate 'true', updatable 'true' );
