CREATE TABLE SERVICESTYPES
(
 ID SERIAL,
 CODE SMALLINT DEFAULT 0,
 LABEL VARCHAR(25) NOT NULL,
 SERVICEFAMILY_ID INTEGER NOT NULL,
 VAT_ID INTEGER NOT NULL,
 ROOMNEEDED BOOLEAN DEFAULT '1' NOT NULL,
 CONSTRAINT PK_SERVICESTYPES_ID PRIMARY KEY (ID),
 CONSTRAINT UQ_SERVICESTYPES_CODEFAMILY UNIQUE (SERVICEFAMILY_ID, CODE),
 CONSTRAINT UQ_SERVICESTYPES_LABEL UNIQUE (LABEL)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_SERVICESTYPES
--BEFORE UPDATE ON SERVICESTYPES
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
