CREATE TABLE CHARGEDSERVICES
(
  SERVICE_ID INTEGER NOT NULL,
  BILL_ID INTEGER NOT NULL,
  RECEPTIONIST_ID INTEGER NOT NULL,
  INVOICINGDATE DATE NOT NULL,
  QUANTITY SMALLINT NOT NULL,
  CHARGEDUNITPRICE DECIMAL,
  VAT_PERCENTAGE DECIMAL,
  ISPRINTED BOOLEAN DEFAULT '0' NOT NULL,
  ISPAYED BOOLEAN DEFAULT '0' NOT NULL,
  PAIEMENTDATE DATE,
  CONSTRAINT PK_CHARGEDSERVICES_SERVICEBILL PRIMARY KEY (SERVICE_ID,BILL_ID),
  CONSTRAINT CK_POS_CHARGEDSERVICES_VAT CHECK (VAT_PERCENTAGE >= 0),
  CONSTRAINT CK_POS_CHARGEDSERVICES_PRICE CHECK (CHARGEDUNITPRICE >= 0)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--CREATE TRIGGER z__minupdate_CHARGEDSERVICES
--BEFORE UPDATE ON CHARGEDSERVICES
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();




CREATE TABLE TRAINING_CHARGEDSERVICES
(
  SERVICE_ID INTEGER NOT NULL,
  BILL_ID INTEGER NOT NULL,
  RECEPTIONIST_ID INTEGER NOT NULL,
  INVOICINGDATE DATE NOT NULL,
  QUANTITY SMALLINT NOT NULL,
  CHARGEDUNITPRICE DECIMAL,
  VAT_PERCENTAGE DECIMAL,
  ISPRINTED BOOLEAN DEFAULT '0' NOT NULL,
  ISPAYED BOOLEAN DEFAULT '0' NOT NULL,
  PAIEMENTDATE DATE,
  CONSTRAINT PK_TRAININGCHARGEDSERVICES_SERVICEBILL PRIMARY KEY (SERVICE_ID,BILL_ID),
  CONSTRAINT CK_POS_TRAININGCHARGEDSERVICES_VAT CHECK (VAT_PERCENTAGE >= 0),
  CONSTRAINT CK_POS_TRAININGCHARGEDSERVICES_PRICE CHECK (CHARGEDUNITPRICE >= 0)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_TRAININGCHARGEDSERVICES
--BEFORE UPDATE ON TRAINING_CHARGEDSERVICES
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
