CREATE TABLE ROOMSOCCUPATIONS
(
  ID SERIAL,
  ROOM_ID INTEGER NOT NULL,
  BILLING_ID INTEGER NOT NULL,
  ARRIVINGDATE DATE NOT NULL,
  DEPARTUREDATE DATE NOT NULL,
  CONSTRAINT PK_ROOMSOCC_ROOMBILLING PRIMARY KEY (ROOM_ID, BILLING_ID),
  CONSTRAINT UQ_ROOMSOCC_ROOMARRIVINGDATE UNIQUE (ROOM_ID, ARRIVINGDATE),
  CONSTRAINT UQ_ROOMSOCC_ROOMDEPARTUREDATE UNIQUE (ROOM_ID, DEPARTUREDATE)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_ROOMSOCCUPATIONS
--BEFORE UPDATE ON ROOMSOCCUPATIONS
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
