CREATE TABLE NATIONALITIES
(
  ID SERIAL,
  CODE VARCHAR(3) NOT NULL,
  COUNTRY VARCHAR(100) NOT NULL,
  LABEL VARCHAR(50) NOT NULL,
  CONSTRAINT PK_NATIONALITIES_ID PRIMARY KEY (ID),
  CONSTRAINT UQ_NATIONALITIES_CODE UNIQUE (CODE),
  CONSTRAINT UQ_NATIONALITIES_NAME UNIQUE (LABEL)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_NATIONALITIES
--BEFORE UPDATE ON NATIONALITIES
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
