CREATE FOREIGN TABLE ADDRESSES_ARCHIVE
(
  ID SERIAL,
  CLIENT_ID INTEGER NOT NULL,
  CONTACT VARCHAR(30) NOT NULL,
  STREET VARCHAR(50) NOT NULL,
  NUMBER VARCHAR(4),
  COMPLEMENTARYLINE VARCHAR(50) NOT NULL,
  CITY VARCHAR(40) NOT NULL,
  ZIPCODE VARCHAR(9),
  COUNTRY VARCHAR(30) NOT NULL,
  PHONE VARCHAR(13)
) SERVER archivesrv OPTIONS ( table_name 'ADDRESSES', use_remote_estimate 'true', updatable 'true' );
