CREATE TABLE CLIENTS
(
  ID SERIAL,
  NAME VARCHAR(35) NOT NULL,
  PHONE VARCHAR(12),
  EMAIL VARCHAR(50),
  IDCARDSCAN VARCHAR(100),
  NATIONALITY_ID INTEGER NOT NULL,
  HOMEADDRESS_ID INTEGER,
  ISCURRENT BOOLEAN DEFAULT '0' NOT NULL,
  CONSTRAINT PK_CLIENTS_ID PRIMARY KEY (ID),
  CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UQ_CLIENTS_NAMEIDCARD UNIQUE (NAME, IDCARDSCAN),
  CONSTRAINT UQ_CLIENTS_NAMEHOME UNIQUE (NAME, HOMEADDRESS_ID),
  CONSTRAINT CK_VAL_CLIENTS_EMAIL CHECK(EMAIL SIMILAR TO '[[[:ALNUM:]\._%\+\-]+@[[:ALNUM:]\.-]+\.[[:ALPHA:]]+]?'),
  CONSTRAINT CK_VAL_CLIENTS_PHONE CHECK(PHONE SIMILAR TO '[[\+|00][[1-9]]{3}[[:DIGIT:]]{8}]?')
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_CLIENTS
--BEFORE UPDATE ON CLIENTS
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
