CREATE TABLE USERS
(
  ID SERIAL,
  LOGIN VARCHAR(20) NOT NULL,
  ENCRYPTEDPASS VARCHAR(255) NOT NULL,
  ISRECEPTIONIST BOOLEAN DEFAULT '0' NOT NULL,
  ISMANAGERX BOOLEAN DEFAULT '0' NOT NULL,
  ISMANAGERZ BOOLEAN DEFAULT '0' NOT NULL,
  ISADMINISTRATOR BOOLEAN DEFAULT '0' NOT NULL,
  CONSTRAINT PK_USERS_ID PRIMARY KEY (ID),
  CONSTRAINT UQ_USERS_LOGIN UNIQUE (LOGIN)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_users
--BEFORE UPDATE ON users
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
