CREATE TABLE SERVICES
(
  ID SERIAL,
  SERVICETYPE_ID INTEGER NOT NULL,
  CODE INTEGER DEFAULT 0,
  NAME VARCHAR(100) NOT NULL,
  ISAVAILABLE BOOLEAN DEFAULT '1'  NOT NULL,
  CONSTRAINT PK_SERVICES_ID PRIMARY KEY (ID),
  CONSTRAINT UQ_SERVICES_NAME UNIQUE (NAME),
  CONSTRAINT UQ_SERVICES_CODETYPE UNIQUE (CODE, SERVICETYPE_ID),
  CONSTRAINT CK_POS_SERVICES_CODE CHECK (CODE >= 0)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_SERVICES
--BEFORE UPDATE ON SERVICES
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
