CREATE TABLE NATIONALITIES
(
  ID SERIAL,
  COUNTRY VARCHAR(511) NOT NULL,
  ISOCODE VARCHAR(2) NOT NULL,
  LONGISOCODE VARCHAR(3) NOT NULL,
  CODE VARCHAR(3) NOT NULL,
  CONSTRAINT PK_NATIONALITIES_ID PRIMARY KEY (ID),
  CONSTRAINT UQ_NATIONALITIES_CODE UNIQUE (CODE),
  CONSTRAINT UQ_NATIONALITIES_ISOCODE UNIQUE (ISOCODE),
  CONSTRAINT UQ_NATIONALITIES_LONGISOCODE UNIQUE (LONGISOCODE),
  CONSTRAINT UQ_NATIONALITIES_COUNTRY UNIQUE (COUNTRY)
) WITH (autovacuum_enabled = 'true', autovacuum_vacuum_threshold = 5);

--suppress_redundant_updates_trigger(); incompatible with upserts!!!
--CREATE TRIGGER z__minupdate_NATIONALITIES
--BEFORE UPDATE ON NATIONALITIES
--FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger();
