ALTER TABLE SERVICESTYPES
 ADD CONSTRAINT FK_SERVICESTYPES_TAXES FOREIGN KEY (VAT_ID) REFERENCES TAXES (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_SERVICESTYPES_FAMILY FOREIGN KEY (SERVICEFAMILY_ID) REFERENCES SERVICESFAMILIES (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SERVICES
 ADD CONSTRAINT FK_SERVICES_TYPE FOREIGN KEY (SERVICETYPE_ID) REFERENCES SERVICESTYPES (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ROOMS
 ADD CONSTRAINT FK_ROOMS_TYPE FOREIGN KEY (ROOMTYPE_ID) REFERENCES ROOMSTYPES (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE CHARGEDSERVICES
 ADD CONSTRAINT FK_CHARGEDSERVICES_USER FOREIGN KEY (RECEPTIONIST_ID) REFERENCES USERS (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_CHARGEDSERVICES_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_CHARGEDSERVICES_BILL FOREIGN KEY (BILL_ID) REFERENCES BILLS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TRAINING_CHARGEDSERVICES
 ADD CONSTRAINT FK_TRAININGCHARGEDSERVICES_TRAINEE FOREIGN KEY (RECEPTIONIST_ID) REFERENCES TRAINEES (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_TRAININGCHARGEDSERVICES_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_TRAININGCHARGEDSERVICES_BILL FOREIGN KEY (BILL_ID) REFERENCES TRAINING_BILLS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE BILLS
 ADD CONSTRAINT FK_BILLS_BILLING FOREIGN KEY (BILLING_ID) REFERENCES BILLINGS (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_BILLS_TYPE FOREIGN KEY (BILLTYPE_ID) REFERENCES BILLSTYPES (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE TRAINING_BILLS
 ADD CONSTRAINT FK_TRAININGBILLS_BILLING FOREIGN KEY (BILLING_ID) REFERENCES TRAINING_BILLINGS (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_TRAININGBILLS_TYPE FOREIGN KEY (BILLTYPE_ID) REFERENCES BILLSTYPES (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ROOMSOCCUPATIONS
 ADD CONSTRAINT FK_ROOMSOCC_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOMS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
 ADD CONSTRAINT FK_ROOMSOCC_BILLINGSID FOREIGN KEY (BILLING_ID) REFERENCES BILLINGS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE BILLINGSGROUPS
 --ADD CONSTRAINT FK_BILLINGSGR_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
 ADD CONSTRAINT FK_BILLINGSGR_BILLINGSID FOREIGN KEY (BILLING_ID) REFERENCES BILLINGS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TRAINING_BILLINGSGROUPS
 --ADD CONSTRAINT FK_TRAININGBILLINGSGR_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
 ADD CONSTRAINT FK_TRAININGBILLINGSGR_BILLINGSID FOREIGN KEY (BILLING_ID) REFERENCES TRAINING_BILLINGS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE BILLINGSCLIENTS
 --ADD CONSTRAINT FK_BILLINGSCL_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
 ADD CONSTRAINT FK_BILLINGSCL_BILLINGSID FOREIGN KEY (BILLING_ID) REFERENCES BILLINGS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TRAINING_BILLINGSCLIENTS
 --ADD CONSTRAINT FK_TRAININGBILLINGSCL_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
 ADD CONSTRAINT FK_TRAININGBILLINGSCL_BILLINGSID FOREIGN KEY (BILLING_ID) REFERENCES TRAINING_BILLINGS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE BILLINGS
 --ADD CONSTRAINT FK_BILLINGS_ADDRESS FOREIGN KEY (BILLINGADDRESS_ID) REFERENCES ADDRESSES_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_BILLINGS_TYPE FOREIGN KEY (BILLINGSTYPE_ID) REFERENCES BILLINGSTYPES (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_BILLINGS_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE TRAINING_BILLINGS
 --ADD CONSTRAINT FK_TRAININGBILLINGS_ADDRESS FOREIGN KEY (BILLINGADDRESS_ID) REFERENCES ADDRESSES_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_TRAININGBILLINGS_TYPE FOREIGN KEY (BILLINGSTYPE_ID) REFERENCES BILLINGSTYPES (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_TRAININGBILLINGS_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES TRAINING_BOOKINGS (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE BOOKINGS
 --ADD CONSTRAINT FK_BOOKINGS_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_BOOKINGS_ROOMTYPE FOREIGN KEY (ROOMTYPE_ID) REFERENCES ROOMSTYPES (ID) ON UPDATE CASCADE ON DELETE NO ACTION;

ALTER TABLE TRAINING_BOOKINGS
 --ADD CONSTRAINT FK_TRAININGBOOKINGS_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS_ARCHIVE (ID) ON UPDATE CASCADE ON DELETE CASCADE,
 ADD CONSTRAINT FK_TRAININGBOOKINGS_ROOMTYPE FOREIGN KEY (ROOMTYPE_ID) REFERENCES ROOMSTYPES (ID) ON UPDATE CASCADE ON DELETE NO ACTION;
