.TH "Répertoire de référence de /home/tiff/Stage-IUT/app/simplhotel/hotel-precheck" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /home/tiff/Stage-IUT/app/simplhotel/hotel-precheck \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBinstall\fP"
.br
.ti -1c
.RI "répertoire \fBsrc\fP"
.br
.in -1c
