.TH "Répertoire de référence de /home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck" 3 "Lundi Juin 24 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBlogic\fP"
.br
.ti -1c
.RI "répertoire \fBmodels\fP"
.br
.ti -1c
.RI "répertoire \fBviews\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBSH_ApplicationCore\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBSH_ApplicationCore\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSH_DatabaseManager\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBSH_DatabaseManager\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSH_MessageManager\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBSH_MessageManager\&.h\fP"
.br
.in -1c
