.TH "md__home_tiff_Stage-IUT_app_simplhotel_hotel-precheck_README" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_tiff_Stage-IUT_app_simplhotel_hotel-precheck_README \- hotel-precheck 
Written with latest stable version of Qt5\&.
.PP
Started as a school diploma-internship for a Swiss hotel\&.
.PP
French short description: Main-courante pour une réception d'hôtel à écran tactile, permettant l'impression de factures pré-check et la gestion d'une archive clients\&.
.PP
English short description: Front-office for a hotel reception with touchscreen, allowing to print billings pre checking and to manage a clients history\&. 
