.TH "QObject" 3 "Vendredi Juin 21 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBSH_ApplicationCore\fP, \fBSH_Company\fP, \fBSH_DatabaseManager\fP, \fBSH_ExtendedQQmlAction\fP, \fBSH_MessageManager\fP\fC [private]\fP, et \fBSH_User\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
