.TH "QSortFilterProxyModel" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QSortFilterProxyModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBSH_ExtendedProxyModel\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
