.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/README.md" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/README.md \- 
.SH SYNOPSIS
.br
.PP
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
