.TH "Rectangle" 3 "Lundi Juin 24 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rectangle \- 
.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBSH_CalendarDialog\fP, \fBSH_OutputZone\fP, \fBSH_RoomsSectionsDelegate\fP, et \fBSH_SqlDataView\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
