.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/logic/SH_AddressCreation.h" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/logic/SH_AddressCreation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SH_IOStateMachine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSH_AddressCreationStateMachine\fP"
.br
.RI "\fILa classe \fBSH_AddressCreationStateMachine\fP fournit une machine d'états finis permettant la création d'un entité 'adresse' à enregistrer dans la base de données\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
