.TH "SH_app" 3 "Vendredi Juin 21 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_app \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBApplicationWindow\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBreload\fP ()"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "alias \fBpages\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 5 du fichier SH_app\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_app::reload ()\fC [signal]\fP"

.SH "Documentation des propriétés"
.PP 
.SS "alias SH_app::pages"

.PP
Définition à la ligne 8 du fichier SH_app\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
