.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/SH_ApplicationCore.cpp" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/SH_ApplicationCore.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SH_ApplicationCore\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'SH_MessageManager\&.h'\fP
.br
\fC#include 'SH_DatabaseManager\&.h'\fP
.br
\fC#include 'logic/SH_ServiceCharging\&.h'\fP
.br
\fC#include 'logic/SH_BillingCreation\&.h'\fP
.br
\fC#include 'models/SH_Trainee\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
