.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/SH_ApplicationCore.h" 3 "Vendredi Juin 21 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/SH_ApplicationCore.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'models/SH_User\&.h'\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include 'logic/SH_IOStateMachine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSH_ApplicationCore\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
