.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/logic/SH_BillingCreation_0.cpp" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/logic/SH_BillingCreation_0.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SH_BillingCreation\&.h'\fP
.br
\fC#include 'SH_StatementState\&.h'\fP
.br
\fC#include 'SH_NumericQuestionState\&.h'\fP
.br
\fC#include 'SH_DateQuestionState\&.h'\fP
.br
\fC#include 'SH_DatabaseContentQuestionState\&.h'\fP
.br
\fC#include 'SH_ConfirmationState\&.h'\fP
.br
\fC#include 'SH_LoopingIOStateMachine\&.h'\fP
.br
\fC#include 'SH_AdaptDatabaseState\&.h'\fP
.br
\fC#include 'SH_ClientCreation\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
