.TH "SH_BillingCreationStateMachine" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_BillingCreationStateMachine \- 
.PP
The \fBSH_BillingCreationStateMachine\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_BillingCreation\&.h>\fP
.PP
Est dérivée de \fBSH_InOutStateMachine\fP\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "virtual void \fBaddChildrenNextTransition\fP (QAbstractState *previousState, QAbstractState *nextState)"
.br
.ti -1c
.RI "virtual void \fBaddChildrenReplaceTransition\fP (QAbstractState *previousState, QAbstractState *nextState)"
.br
.ti -1c
.RI "void \fBaddIOState\fP (\fBSH_InOutState\fP *state, QString field)"
.br
.ti -1c
.RI "void \fBaddIOStateMachine\fP (\fBSH_InOutStateMachine\fP *fsm)"
.br
.ti -1c
.RI "void \fBsetContentValue\fP (QVariant content, QString field)"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBcancelReplacement\fP ()"
.br
.ti -1c
.RI "void \fBclearAll\fP ()"
.br
.ti -1c
.RI "void \fBconfirmInput\fP ()"
.br
.ti -1c
.RI "void \fBdisplayCalendar\fP ()"
.br
.ti -1c
.RI "void \fBdisplayFileDialog\fP ()"
.br
.ti -1c
.RI "void \fBgoNext\fP ()"
.br
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBreceiveInput\fP (QString input)"
.br
.ti -1c
.RI "void \fBreplaceInput\fP (QString field)"
.br
.ti -1c
.RI "void \fBresendText\fP (QString text, bool editable=false)"
.br
.ti -1c
.RI "void \fBsendText\fP (QString text, bool editable=false)"
.br
.ti -1c
.RI "void \fBvalidateInput\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSH_BillingCreationStateMachine\fP (QString \fBname\fP, \fBQObject\fP *parent=0)"
.br
.RI "\fI\fBSH_BillingCreationStateMachine\fP\&. \fP"
.ti -1c
.RI "QVariant \fBgetContentValue\fP (QString field)"
.br
.ti -1c
.RI "QHistoryState * \fBhistoryValue\fP (QString field)"
.br
.ti -1c
.RI "QVariantMap \fBioContent\fP () const "
.br
.ti -1c
.RI "bool \fBisRunning\fP ()"
.br
.ti -1c
.RI "void \fBsetIOcontent\fP (const QVariantMap &\fBioContent\fP)"
.br
.ti -1c
.RI "void \fBsetIOStateHistory\fP (QHistoryState *state, QString field)"
.br
.ti -1c
.RI "void \fBsetTableName\fP (const QString &\fBtableName\fP)"
.br
.ti -1c
.RI "QString \fBtableName\fP () const "
.br
.ti -1c
.RI "QString \fBtoString\fP ()"
.br
.in -1c
.SS "Connecteurs protégés"

.in +1c
.ti -1c
.RI "void \fBemitGoNext\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "QMap< QString, QHistoryState * > \fBioStatesHistory\fP () const "
.br
.ti -1c
.RI "bool \fBisERunning\fP ()"
.br
.ti -1c
.RI "void \fBonEntry\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBonExit\fP (QEvent *event)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "QVariantMap \fBm_ioContent\fP"
.br
.ti -1c
.RI "QMap< QString, QHistoryState * > \fBm_ioStatesHistory\fP"
.br
.ti -1c
.RI "QString \fBm_tableName\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
The \fBSH_BillingCreationStateMachine\fP class\&. 
.PP
Définition à la ligne 7 du fichier SH_BillingCreation\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "SH_BillingCreationStateMachine::SH_BillingCreationStateMachine (QStringname, \fBQObject\fP *parent = \fC0\fP)"

.PP
\fBSH_BillingCreationStateMachine\fP\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIname\fP 
.br
\fIparent\fP \fBSH_BillingCreationStateMachine::SH_BillingCreationStateMachine\fP 
.RE
.PP

.PP
Définition à la ligne 14 du fichier SH_BillingCreation\&.cpp\&.
.PP
Références SH_LoopingInOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), SH_QuestionState::answerInvalid(), SH_InOutStateMachine::confirmInput(), SH_LoopingInOutStateMachine::current(), SH_InOutStateMachine::getContentValue(), SH_QuestionState::givenAnswer(), SH_GenericState::goNext(), SH_AdaptDatabaseState::insertUpdate(), SH_InOutStateMachine::m_ioContent, SH_InOutStateMachine::m_tableName, SH_GenericStateMachine::next(), SH_InOutStateMachine::setContentValue(), SH_LoopingInOutStateMachine::setLimit(), SH_LoopingInOutStateMachine::setPersistentContentValue(), SH_LoopingInOutStateMachine::stopLooping(), et SH_GenericStateMachine::toString()\&.
.PP
.nf
14                                                                                             :
15     SH_InOutStateMachine("BILLINGS",name, parent)
16 {
17     qDebug() << "facturation";
18 
19     SH_StatementState* intro = new SH_StatementState("Création d'une facturation", "intro billing creation");
20     SH_NumericQuestionState* nbAdults = new SH_NumericQuestionState("Veuillez entrer le nombre d'adultes","adults billing creation", 0);
21     SH_NumericQuestionState* nbChildren = new SH_NumericQuestionState("Veuillez entrer le nombre d'enfants", "children billing creation", 0);
22     SH_DateQuestionState* arrivingDate = new SH_DateQuestionState("Veuillez entrer la date d'arrivée", "arriving date billing creation", true,true);
23     SH_DateQuestionState* departureDate = new SH_DateQuestionState("Veuillez entrer la date de départ prévue", "departure date billing creation", false,true);
24     SH_DatabaseContentQuestionState* client = new SH_DatabaseContentQuestionState("Veuillez entrer le nom du client à facturer","main client billing creation", "CLIENTS", "NAME");
25     SH_ClientCreationStateMachine* clientCreation = new SH_ClientCreationStateMachine("main client creation in billing creation");
26     SH_NumericQuestionState* nbRooms = new SH_NumericQuestionState("Veuillez entrer le nombre de chambres", "nb rooms billing creation", 1);
27     /*DatabaseContentQuestionState* type = new DatabaseContentQuestionState("Veuillez choisir le type de facturation","billing type billing creation", "BILLINGSTYPES", "CODE");*/
28     SH_DatabaseContentQuestionState* type = new SH_DatabaseContentQuestionState("Veuillez choisir le type de facturation","billing type billing creation", "BILLINGSTYPES", "ID");
29     SH_LoopingInOutStateMachine* roomsAffectation = new SH_LoopingInOutStateMachine("ROOMSOCCUPATION", "rooms affectation billing creation");
30     SH_LoopingInOutStateMachine* billsCreation = new SH_LoopingInOutStateMachine("BILLS", "bills creation billing creation");
31     SH_LoopingInOutStateMachine* clientList = new SH_LoopingInOutStateMachine("CLIENTS", "bills creation billing creation");
32     SH_ConfirmationState* confirmPart1 = new SH_ConfirmationState("Veuillez appuyer sur la touche \"CONFIRMER\" pour passer à l'étape suivante", "confirm part 1");
33     SH_AdaptDatabaseState* saveState = new SH_AdaptDatabaseState("enregistrement de la machine "+toString());
34     SH_ConfirmationState* confirmAll = new SH_ConfirmationState("Veuillez appuyer sur la touche \"CONFIRMER\" pour passer à l'étape suivante", "confirm all");
35     QFinalState* final = new QFinalState();
36 
37 
38 
39     connect(nbAdults, &SH_GenericState::exited, [=]() {
40         clientList->setLimit(getContentValue("NBADULTS")\&.toInt()-1);
41     });
42 
43     connect(nbRooms, &SH_GenericState::exited, [=]() {
44         roomsAffectation->setLimit(getContentValue("NBROOMS")\&.toInt());
45     });
46 
47     connect(type, &SH_GenericState::exited, [=]() {
48         billsCreation->setLimit(getContentValue("NBROOMS")\&.toInt() * (getContentValue("BILLINGTYPE_ID")\&.toInt() % 3));
49     });
50 
51     connect(saveState, &SH_GenericState::exited, [=]() {
52         roomsAffectation->setPersistentContentValue(getContentValue("ID"), "BILLING_ID");
53         billsCreation->setPersistentContentValue(getContentValue("ID"), "BILLING_ID");
54     });
55 
56 
57 
58 
59 
60     SH_DatabaseContentQuestionState* rooms = new SH_DatabaseContentQuestionState("Veuillez entrer un numéro de chambre","room billing creation", "ROOMS", "NUMBER");
61     QFinalState* finalRooms = new QFinalState();
62     roomsAffectation->addChildrenNextTransition(rooms, finalRooms);
63     roomsAffectation->addIOState(rooms,"ROOM_NUMBER");
64     roomsAffectation->addState(finalRooms);
65     roomsAffectation->setInitialState(rooms);
66 
67 
68 
69     SH_DatabaseContentQuestionState* supplClient = new SH_DatabaseContentQuestionState("Veuillez entrer le nom du client (adulte) supplémentaire ou appuyer sur la touche \"CONFIRMER\" pour passer à la suite de la facturation","other client billing creation", "CLIENTS", "NAME");
70     SH_ClientCreationStateMachine* supplClientCreation = new SH_ClientCreationStateMachine("other client creation in billing creation");
71     connect(clientList, &SH_InOutStateMachine::confirmInput, [=]() {
72         clientList->stopLooping();
73         emit supplClient->goNext();
74     });
75     QFinalState* finalClients = new QFinalState();
76     clientList->addChildrenNextTransition(supplClient, finalClients);
77     connect(supplClient, &SH_QuestionState::answerInvalid, [=]() {
78         supplClientCreation->setContentValue(supplClient->givenAnswer(), "NAME");
79         supplClient->addTransition(supplClient, SIGNAL(next()), supplClientCreation);
80         emit supplClient->goNext();
81     });
82     clientList->addChildrenNextTransition(supplClientCreation, finalClients);
83     clientList->addState(finalClients);
84     clientList->addState(supplClient);
85     clientList->setInitialState(supplClient);
86 
87 
88 
89 
90     QFinalState* finalBills = new QFinalState();
91     SH_GenericState* bills = new SH_GenericState("bill id attribution");
92     connect(bills, &SH_GenericState::entered, [=]() {
93         this->setContentValue(QVariant(billsCreation->current()), "BILLINGBILL_ID");
94         int billingType = getContentValue("BILLINGTYPE_ID")\&.toInt();
95         int billType;
96         if(billingType <= 2) {
97             billType = 1+billingType; /*nb facture par chambre*/
98         } else {
99             billType = (billsCreation->current() % (1+(billingType % 3)));
100         }
101 
102         this->setContentValue(QVariant(billType), "BILLTYPE_ID");
103         emit bills->goNext();
104     });
105     billsCreation->addChildrenNextTransition(bills, finalBills);
106     billsCreation->addState(finalBills);
107     billsCreation->addState(bills);
108     billsCreation->setInitialState(bills);
109 
110 
111 
112 
113     this->addChildrenNextTransition(intro, nbAdults);
114     this->addChildrenNextTransition(nbAdults, nbChildren);
115     this->addChildrenNextTransition(nbChildren, arrivingDate);
116     this->addChildrenNextTransition(arrivingDate, departureDate);
117     this->addChildrenNextTransition(departureDate, client);
118     this->addChildrenNextTransition(client, nbRooms);
119     connect(client, &SH_QuestionState::answerInvalid, [=]() {
120         clientCreation->setContentValue(client->givenAnswer(),"NAME");
121         client->addTransition(client, SIGNAL(next()), clientCreation);
122         emit client->goNext();
123     });
124     this->addChildrenNextTransition(clientCreation, nbRooms);
125     this->addChildrenNextTransition(nbRooms, type);
126     confirmPart1->addTransition(confirmPart1, SIGNAL(next()), saveState);
127     connect(confirmPart1, &SH_GenericState::exited, [=]() {
128         setContentValue(saveState->insertUpdate(m_tableName, m_ioContent), "ID");
129     });
130     this->addChildrenNextTransition(type, confirmPart1);
131     saveState->addTransition(saveState, SIGNAL(next()),roomsAffectation);
132     this->addChildrenNextTransition(roomsAffectation, billsCreation);
133     this->addChildrenNextTransition(billsCreation, clientList);
134     this->addChildrenNextTransition(clientList, confirmAll);
135     this->addChildrenNextTransition(confirmAll, final);
136 
137     this->addIOState(intro,"");
138     this->addIOState(nbAdults,"NBADULTS");
139     this->addIOState(nbChildren,"NBCHILDREN");
140     this->addIOState(arrivingDate,"ARRIVINGDATE");
141     this->addIOState(departureDate,"EXPECTEDDEPARTUREDATE");
142     this->addIOState(client,"CLIENT_ID");
143     this->addIOState(nbRooms,"NBROOMS");
144     this->addIOState(type,"BILLINGTYPE_ID");
145     this->addIOState(confirmPart1,"");
146     this->addIOState(confirmAll,"");
147     this->addIOStateMachine(billsCreation);
148     this->addIOStateMachine(roomsAffectation);
149     this->addIOStateMachine(clientList);
150     this->addState(saveState);
151     this->addState(final);
152 
153     this->setInitialState(intro);
154 }
.fi
.SH "Documentation des fonctions membres"
.PP 
.SS "SH_InOutStateMachine::addChildrenNextTransition (QAbstractState *previousState, QAbstractState *nextState)\fC [virtual]\fP, \fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIpreviousState\fP 
.br
\fInextState\fP 
.RE
.PP

.PP
Réimplémentée dans \fBSH_LoopingInOutStateMachine\fP\&.
.PP
Définition à la ligne 260 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_GenericStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::clearAll(), SH_AdaptDatabaseState::insertUpdate(), SH_InOutStateMachine::m_ioContent, SH_InOutStateMachine::m_tableName, SH_GenericStateMachine::next(), SH_InOutStateMachine::sendText(), SH_InOutStateMachine::setContentValue(), et SH_GenericStateMachine::toString()\&.
.PP
Référencé par SH_BillingCreationStateMachine(), et SH_ClientCreationStateMachine::SH_ClientCreationStateMachine()\&.
.PP
.nf
261 {
262     SH_GenericStateMachine* fsmPreviousState = qobject_cast<SH_GenericStateMachine*>(previousState);
263     SH_GenericState* genPreviousState = qobject_cast<SH_GenericState*>(previousState);
264     QFinalState* final = qobject_cast<QFinalState*>(nextState);
265     if(final) {
266         SH_AdaptDatabaseState* saveState = new SH_AdaptDatabaseState("enregistrement de la machine "+toString());
267         if(genPreviousState) {
268             genPreviousState->addTransition(genPreviousState, SIGNAL(next()), saveState);
269         }
270         if(fsmPreviousState) {
271             fsmPreviousState->addTransition(fsmPreviousState, SIGNAL(next()), saveState);
272         }
273         if(genPreviousState || fsmPreviousState) {
274             connect(previousState, &QAbstractState::exited, [=]() {
275                 connect(saveState, &QAbstractState::entered, [=]() {
276                     emit this->sendText("Merci !");
277                     setContentValue(saveState->insertUpdate(m_tableName, m_ioContent), "ID");
278                     emit this->clearAll();
279                 });
280             });
281             saveState->addTransition(saveState, SIGNAL(next()),final);
282         }
283     }
284     SH_GenericStateMachine::addChildrenNextTransition(previousState, nextState);
285 }
.fi
.SS "SH_InOutStateMachine::addChildrenReplaceTransition (QAbstractState *previousState, QAbstractState *nextState)\fC [virtual]\fP, \fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIpreviousState\fP 
.br
\fInextState\fP 
.RE
.PP

.PP
Définition à la ligne 236 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::historyValue(), SH_GenericState::isRunning(), SH_GenericStateMachine::next(), et SH_InOutStateMachine::replaceInput()\&.
.PP
Référencé par SH_LoopingInOutStateMachine::addChildrenNextTransition()\&.
.PP
.nf
237 {
238         SH_GenericState* genPreviousState = qobject_cast<SH_GenericState*>(previousState);
239     if(genPreviousState) {
240         /*à faire au moment de l'entrée dans l'état previousState*/
241         connect(this, &SH_InOutStateMachine::replaceInput, [=](QString field) {
242             if(genPreviousState->isRunning()) {
243                 /*après avoir demandé à revenir sur un état précédent, on attend la fin de l'état actuel puis on retourne à l'historique de l'état désiré; celui-ci fini, on passe à l'état qui aurait du suivre celui pendant lequel on a demandé à revenir sur un état précédent*/
244                 QHistoryState* hState = historyValue(field);
245                 if(hState) { /*si l'historique existe (on a déjà quitté l'état voulu)*/
246                     hState->parentState()->addTransition(hState->parentState(), SIGNAL(next()), nextState);
247                     genPreviousState->addTransition(genPreviousState, SIGNAL(next()), hState);
248                 }
249             }
250         });
251     }
252 }
.fi
.SS "SH_InOutStateMachine::addIOState (\fBSH_InOutState\fP *state, QStringfield)\fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP 
.br
\fIfield\fP 
.RE
.PP

.PP
Définition à la ligne 94 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_ConfirmationState::confirmInput(), SH_InOutState::display(), SH_InOutStateMachine::displayCalendar(), SH_InOutStateMachine::displayFileDialog(), SH_InOutState::output(), SH_InOutState::rawInput(), SH_InOutStateMachine::receiveInput(), SH_InOutState::resendInput(), SH_InOutStateMachine::resendText(), SH_InOutState::sendOutput(), SH_InOutStateMachine::sendText(), SH_InOutStateMachine::setContentValue(), SH_InOutState::setInput(), SH_InOutStateMachine::setIOStateHistory(), SH_InOutState::setOutput(), SH_GenericState::toString(), SH_InOutStateMachine::validateInput(), et SH_InOutState::visibility()\&.
.PP
Référencé par SH_BillingCreationStateMachine(), SH_ClientCreationStateMachine::SH_ClientCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
95 {
96     /*à faire au moment de l'entrée dans l'état state*/
97     connect(state, &QState::entered, [=]() {
98         qDebug() << state->toString() << "entered !";
99         state->display(true);
100         connect(this, &SH_InOutStateMachine::receiveInput, state, &SH_InOutState::setInput, Qt::QueuedConnection); /* la réception d'une valeur entraîne son enregistrement comme entrée de l'utilisateur auprès de l'état*/
101         connect(this, &SH_InOutStateMachine::receiveInput, [=](QString in){ qDebug() << state->toString() << "hello world !"; state->setInput(in);}); /* la réception d'une valeur entraîne son enregistrement comme entrée de l'utilisateur auprès de l'état*/
102         connect(state, &SH_InOutState::setOutput, [=](QVariant out) {qDebug() << state->toString() << "out !";});
103         connect(state, &SH_InOutState::sendOutput, [=](QVariant out) {qDebug() << state->toString() << "connected !"; emit this->sendText(out\&.toString(), false);});
104         connect(state, &SH_InOutState::resendInput, [=](QVariant in) {emit this->resendText(in\&.toString(), true);});
105         if(state->visibility()) {
106             state->sendOutput(QVariant(state->output()));
107         } else {
108             qDebug() << "invisible";
109         }
110     });
111     SH_ValidationState *validationState = qobject_cast<SH_ValidationState*>(state);
112     if(validationState) {
113         /*à faire au moment de l'entrée dans l'état state*/
114         connect(validationState, &QState::entered, [=]() {
115             connect(this, &SH_InOutStateMachine::validateInput, validationState, &SH_ValidationState::confirmInput, Qt::QueuedConnection);
116         });
117     }
118     SH_ConfirmationState *confirmationState = qobject_cast<SH_ConfirmationState*>(state);
119     if(confirmationState) {
120         /*à faire au moment de l'entrée dans l'état state*/
121         connect(confirmationState, &QState::entered, [=]() {
122             connect(this, &SH_InOutStateMachine::validateInput, confirmationState, &SH_ConfirmationState::confirmInput, Qt::QueuedConnection);
123         });
124     }
125     SH_DateQuestionState *dateState = qobject_cast<SH_DateQuestionState*>(state);
126     if(dateState) {
127         /*à faire au moment de l'entrée dans l'état state*/
128         connect(dateState, &QState::entered, this, &SH_InOutStateMachine::displayCalendar, Qt::QueuedConnection);
129     }
130     SH_FileSelectionState *fileState = qobject_cast<SH_FileSelectionState*>(state);
131     if(fileState) {
132         /*à faire au moment de l'entrée dans l'état state*/
133         connect(fileState, &QState::entered, this, &SH_InOutStateMachine::displayFileDialog, Qt::QueuedConnection);
134     }
135     /*à faire au moment de la sortie de l'état state*/
136     connect(state, &QState::exited, [=]() {
137         qDebug() << "exited !";
138         if(!field\&.isEmpty()) {
139             setContentValue(state->rawInput(), field);
140             /*gestion de l'historique des états pour pouvoir revenir à l'état state après l'avoir quitté*/
141             QHistoryState* hState = new QHistoryState(state);
142             setIOStateHistory(hState, field);
143         }
144         state->disconnect(this); /*plus aucune action sur l'état ne pourra être provoquée par la machine*/
145     });
146 
147 
148     QAbstractState* astate = qobject_cast<QAbstractState *>(state);
149     if(astate) {
150         addState(astate);
151     }
152 }
.fi
.SS "SH_InOutStateMachine::addIOStateMachine (\fBSH_InOutStateMachine\fP *fsm)\fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfsm\fP 
.RE
.PP

.PP
Définition à la ligne 160 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::cancelReplacement(), SH_InOutStateMachine::confirmInput(), SH_InOutStateMachine::displayCalendar(), SH_InOutStateMachine::receiveInput(), SH_InOutStateMachine::replaceInput(), SH_InOutStateMachine::resendText(), SH_InOutStateMachine::sendText(), et SH_InOutStateMachine::validateInput()\&.
.PP
Référencé par SH_BillingCreationStateMachine()\&.
.PP
.nf
161 {
162     /*à faire au moment de l'entrée dans la machine d'état fsm*/
163     connect(fsm, &QState::entered, [=]() {
164         connect(this, &SH_InOutStateMachine::receiveInput, fsm, &SH_InOutStateMachine::receiveInput,Qt::QueuedConnection);
165         connect(this, &SH_InOutStateMachine::sendText, fsm, &SH_InOutStateMachine::sendText,Qt::QueuedConnection);
166         connect(this, &SH_InOutStateMachine::resendText, fsm, &SH_InOutStateMachine::resendText,Qt::QueuedConnection);
167         connect(this, &SH_InOutStateMachine::confirmInput, fsm, &SH_InOutStateMachine::confirmInput,Qt::QueuedConnection);
168         connect(this, &SH_InOutStateMachine::validateInput, fsm, &SH_InOutStateMachine::validateInput,Qt::QueuedConnection);
169         connect(this, &SH_InOutStateMachine::replaceInput, fsm, &SH_InOutStateMachine::replaceInput,Qt::QueuedConnection);
170         connect(this, &SH_InOutStateMachine::cancelReplacement, fsm, &SH_InOutStateMachine::cancelReplacement,Qt::QueuedConnection);
171         connect(this, &SH_InOutStateMachine::displayCalendar, fsm, &SH_InOutStateMachine::displayCalendar,Qt::QueuedConnection);
172     });
173     /*à faire au moment de la sortie de la machine d'état fsm*/
174     connect(fsm, &QState::exited, [=]() {
175         fsm->disconnect(this); /*plus aucune action sur la machine d'état fille ne pourra être provoquée par la machine mère*/
176     });
177 
178 }
.fi
.SS "SH_InOutStateMachine::cancelReplacement ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::cancelReplacement()\&.
.SS "SH_InOutStateMachine::clearAll ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addChildrenNextTransition(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::confirmInput ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOStateMachine(), SH_ApplicationCore::receiveConfirmation(), SH_BillingCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "SH_InOutStateMachine::displayCalendar ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::displayFileDialog ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.SS "void SH_GenericStateMachine::emitGoNext ()\fC [protected]\fP, \fC [slot]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 58 du fichier SH_GenericDebugableStateMachine\&.cpp\&.
.PP
Références SH_GenericStateMachine::isRunning(), et SH_GenericStateMachine::next()\&.
.PP
Référencé par SH_GenericStateMachine::SH_GenericStateMachine()\&.
.PP
.nf
59 {
60     if(isRunning()) {
61         emit next();
62     }
63 }
.fi
.SS "SH_InOutStateMachine::getContentValue (QStringfield)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfield\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
QVariant 
.RE
.PP

.PP
Définition à la ligne 49 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioContent\&.
.PP
Référencé par SH_BillingCreationStateMachine(), et SH_ClientCreationStateMachine::SH_ClientCreationStateMachine()\&.
.PP
.nf
50 {
51     return m_ioContent\&.value(field);
52 }
.fi
.SS "SH_GenericStateMachine::goNext ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_AddressCreationStateMachine::SH_AddressCreationStateMachine(), et SH_GenericStateMachine::SH_GenericStateMachine()\&.
.SS "SH_InOutStateMachine::historyValue (QStringfield)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfield\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
QHistoryState 
.RE
.PP

.PP
Définition à la ligne 223 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioStatesHistory\&.
.PP
Référencé par SH_LoopingInOutStateMachine::addChildrenNextTransition(), et SH_InOutStateMachine::addChildrenReplaceTransition()\&.
.PP
.nf
224 {
225     return m_ioStatesHistory\&.value(field);
226 }
.fi
.SS "SH_InOutStateMachine::ioContent () const\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QVariantMap 
.RE
.PP

.PP
Définition à la ligne 27 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioContent\&.
.PP
Référencé par SH_InOutStateMachine::setIOcontent()\&.
.PP
.nf
28 {
29     return m_ioContent;
30 }
.fi
.SS "SH_InOutStateMachine::ioStatesHistory () const\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QMap<QString, QHistoryState *> 
.RE
.PP

.PP
Définition à la ligne 187 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioStatesHistory\&.
.PP
Référencé par SH_InOutStateMachine::setIOStatesHistory()\&.
.PP
.nf
188 {
189     return m_ioStatesHistory;
190 }
.fi
.SS "SH_InOutStateMachine::isERunning ()\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.SS "SH_GenericStateMachine::isRunning ()\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne 47 du fichier SH_GenericDebugableStateMachine\&.cpp\&.
.PP
Références SH_GenericStateMachine::m_isRunning\&.
.PP
Référencé par SH_ApplicationCore::cancelRunningThread(), SH_ApplicationCore::connectRunningThread(), et SH_GenericStateMachine::emitGoNext()\&.
.PP
.nf
48 {
49     return m_isRunning;
50 }
.fi
.SS "SH_GenericStateMachine::next ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_GenericStateMachine::addChildrenNextTransition(), SH_LoopingInOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenReplaceTransition(), SH_GenericStateMachine::emitGoNext(), et SH_BillingCreationStateMachine()\&.
.SS "SH_GenericStateMachine::onEntry (QEvent *event)\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIevent\fP 
.RE
.PP

.PP
Définition à la ligne 72 du fichier SH_GenericDebugableStateMachine\&.cpp\&.
.PP
Références SH_GenericStateMachine::m_isRunning, et SH_NamedObject::name()\&.
.PP
.nf
73 {
74     m_isRunning = true;
75     this->blockSignals(!m_isRunning);
76     qDebug() << "Machine: " << machine()->objectName() << " entered " << this->name();
77 }
.fi
.SS "SH_GenericStateMachine::onExit (QEvent *event)\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIevent\fP 
.RE
.PP

.PP
Définition à la ligne 85 du fichier SH_GenericDebugableStateMachine\&.cpp\&.
.PP
Références SH_GenericStateMachine::m_isRunning, et SH_NamedObject::name()\&.
.PP
.nf
86 {
87     m_isRunning = false;
88     this->blockSignals(!m_isRunning);
89     qDebug() << "Machine: " << machine()->objectName() << " exited  " << name();
90 }
.fi
.SS "SH_InOutStateMachine::receiveInput (QStringinput)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIinput\fP 
.RE
.PP

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), SH_ApplicationCore::receiveInput(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "SH_InOutStateMachine::replaceInput (QStringfield)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfield\fP 
.RE
.PP

.PP
Référencé par SH_LoopingInOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenReplaceTransition(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::replaceInput()\&.
.SS "void SH_InOutStateMachine::resendText (QStringtext, booleditable = \fCfalse\fP)\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::sendText (QStringtext, booleditable = \fCfalse\fP)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fItext\fP 
.br
\fIeditable\fP 
.RE
.PP

.PP
Référencé par SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::setContentValue (QVariantcontent, QStringfield)\fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIcontent\fP 
.br
\fIfield\fP 
.RE
.PP

.PP
Définition à la ligne 83 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioContent\&.
.PP
Référencé par SH_LoopingInOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addIOState(), SH_ApplicationCore::launchBillThread(), SH_BillingCreationStateMachine(), et SH_ClientCreationStateMachine::SH_ClientCreationStateMachine()\&.
.PP
.nf
84 {
85     m_ioContent\&.insert(field, content);
86 }
.fi
.SS "SH_InOutStateMachine::setIOcontent (const QVariantMap &ioContent)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIioContent\fP 
.RE
.PP

.PP
Définition à la ligne 38 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::ioContent(), et SH_InOutStateMachine::m_ioContent\&.
.PP
.nf
39 {
40     m_ioContent = ioContent;
41 }
.fi
.SS "SH_InOutStateMachine::setIOStateHistory (QHistoryState *state, QStringfield)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP 
.br
\fIfield\fP 
.RE
.PP

.PP
Définition à la ligne 211 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioStatesHistory\&.
.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.PP
.nf
212 {
213     m_ioStatesHistory\&.insert(field, state); /*remplacement si plusieurs fois*/
214 }
.fi
.SS "SH_InOutStateMachine::setTableName (const QString &tableName)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fItableName\fP 
.RE
.PP

.PP
Définition à la ligne 71 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_tableName, et SH_InOutStateMachine::tableName()\&.
.PP
.nf
72 {
73     m_tableName = tableName;
74 }
.fi
.SS "SH_InOutStateMachine::tableName () const\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 60 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_tableName\&.
.PP
Référencé par SH_InOutStateMachine::setTableName()\&.
.PP
.nf
61 {
62     return m_tableName;
63 }
.fi
.SS "SH_GenericStateMachine::toString ()\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Réimplémentée à partir de \fBSH_NamedObject\fP\&.
.PP
Définition à la ligne 30 du fichier SH_GenericDebugableStateMachine\&.cpp\&.
.PP
Références SH_NamedObject::toString(), et SH_GenericState::toString()\&.
.PP
Référencé par SH_GenericStateMachine::addChildrenNextTransition(), SH_LoopingInOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_ApplicationCore::launchBillingsThread(), SH_BillingCreationStateMachine(), SH_GenericStateMachine::SH_GenericStateMachine(), et SH_GenericState::toString()\&.
.PP
.nf
31 {
32     QObject* parent = this->parent();
33     SH_GenericState* par = qobject_cast<SH_GenericState *>(parent);
34     if(par) {
35         return SH_NamedObject::toString()+ " [descending from "+par->toString()+"] ";
36     } else {
37         return SH_NamedObject::toString();
38     }
39 }
.fi
.SS "SH_InOutStateMachine::validateInput ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), SH_ApplicationCore::receiveValidation(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SH "Documentation des données membres"
.PP 
.SS "SH_InOutStateMachine::m_ioContent\fC [protected]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 216 du fichier SH_IOStateMachine\&.h\&.
.PP
Référencé par SH_LoopingInOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::getContentValue(), SH_InOutStateMachine::ioContent(), SH_InOutStateMachine::setContentValue(), SH_InOutStateMachine::setIOcontent(), et SH_BillingCreationStateMachine()\&.
.SS "SH_InOutStateMachine::m_ioStatesHistory\fC [protected]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 228 du fichier SH_IOStateMachine\&.h\&.
.PP
Référencé par SH_InOutStateMachine::historyValue(), SH_InOutStateMachine::ioStatesHistory(), SH_InOutStateMachine::setIOStateHistory(), et SH_InOutStateMachine::setIOStatesHistory()\&.
.SS "SH_InOutStateMachine::m_tableName\fC [protected]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 222 du fichier SH_IOStateMachine\&.h\&.
.PP
Référencé par SH_LoopingInOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::setTableName(), SH_BillingCreationStateMachine(), et SH_InOutStateMachine::tableName()\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
