.TH "SH_Company" 3 "Vendredi Juin 21 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_Company \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_Company\&.h>\fP
.PP
Est dérivée de \fBQObject\fP\&.
.SH "Description détaillée"
.PP 
Définition à la ligne 12 du fichier SH_Company\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
