.TH "SH_ContentView" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_ContentView \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBGridLayout\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBselected\fP (string selectedItem)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBaddFilterIndex\fP (index)"
.br
.ti -1c
.RI "void \fBfilter\fP (index, remove)"
.br
.ti -1c
.RI "void \fBremoveFilterIndex\fP (index)"
.br
.ti -1c
.RI "void \fBsort\fP (index)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "variant \fBactiveFilterIndicatorIndexes\fP"
.br
.ti -1c
.RI "string \fBdataDelegate\fP"
.br
.ti -1c
.RI "string \fBemptyDelegate\fP"
.br
.ti -1c
.RI "alias \fBmodel\fP"
.br
.ti -1c
.RI "string \fBsectionDelegate\fP"
.br
.ti -1c
.RI "alias \fBsectionIndex\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_ContentView\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_ContentView::addFilterIndex (index)"

.SS "void SH_ContentView::filter (index, remove)"

.SS "void SH_ContentView::removeFilterIndex (index)"

.SS "void SH_ContentView::selected (stringselectedItem)\fC [signal]\fP"

.SS "void SH_ContentView::sort (index)"

.SH "Documentation des propriétés"
.PP 
.SS "variant SH_ContentView::activeFilterIndicatorIndexes"

.PP
Définition à la ligne 13 du fichier SH_ContentView\&.qml\&.
.SS "string SH_ContentView::dataDelegate"

.PP
Définition à la ligne 7 du fichier SH_ContentView\&.qml\&.
.SS "string SH_ContentView::emptyDelegate"

.PP
Définition à la ligne 9 du fichier SH_ContentView\&.qml\&.
.SS "alias SH_ContentView::model"

.PP
Définition à la ligne 17 du fichier SH_ContentView\&.qml\&.
.SS "string SH_ContentView::sectionDelegate"

.PP
Définition à la ligne 11 du fichier SH_ContentView\&.qml\&.
.SS "alias SH_ContentView::sectionIndex"

.PP
Définition à la ligne 15 du fichier SH_ContentView\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
