.TH "SH_ConnexionPage" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_ConnexionPage \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBItem\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBcheckUsername\fP (string name)"
.br
.ti -1c
.RI "void \fBloggedIn\fP ()"
.br
.ti -1c
.RI "void \fBlogIn\fP (string login, string password)"
.br
.ti -1c
.RI "void \fBreload\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_ConnexionPage\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_ConnexionPage::checkUsername (stringname)\fC [signal]\fP"

.SS "void SH_ConnexionPage::loggedIn ()\fC [signal]\fP"

.SS "void SH_ConnexionPage::logIn (stringlogin, stringpassword)\fC [signal]\fP"

.SS "void SH_ConnexionPage::reload ()\fC [signal]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
