.TH "SH_CommonPage" 3 "Vendredi Juin 21 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_CommonPage \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBItem\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBcancelProcess\fP ()"
.br
.ti -1c
.RI "void \fBcancelReplace\fP ()"
.br
.ti -1c
.RI "void \fBconfirm\fP ()"
.br
.ti -1c
.RI "void \fBkeySelected\fP (string selectedKey)"
.br
.ti -1c
.RI "void \fBquit\fP ()"
.br
.ti -1c
.RI "void \fBreload\fP ()"
.br
.ti -1c
.RI "void \fBreplace\fP (string field)"
.br
.ti -1c
.RI "void \fBselected\fP (string selectedItem)"
.br
.ti -1c
.RI "void \fBvalidate\fP ()"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "QtObject \fBstreamBuffer\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_CommonPage\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_CommonPage::cancelProcess ()\fC [signal]\fP"

.SS "void SH_CommonPage::cancelReplace ()\fC [signal]\fP"

.SS "void SH_CommonPage::confirm ()\fC [signal]\fP"

.SS "void SH_CommonPage::keySelected (stringselectedKey)\fC [signal]\fP"

.SS "void SH_CommonPage::quit ()\fC [signal]\fP"

.SS "void SH_CommonPage::reload ()\fC [signal]\fP"

.SS "void SH_CommonPage::replace (stringfield)\fC [signal]\fP"

.SS "void SH_CommonPage::selected (stringselectedItem)\fC [signal]\fP"

.SS "void SH_CommonPage::validate ()\fC [signal]\fP"

.SH "Documentation des propriétés"
.PP 
.SS "QtObject SH_CommonPage::streamBuffer"

.PP
Définition à la ligne 7 du fichier SH_CommonPage\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
