.TH "SH_DecimalQuestionState" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_DecimalQuestionState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_DecimalQuestionState\&.h>\fP
.PP
Est dérivée de \fBSH_QuestionState\fP\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "virtual void \fBsetOutput\fP (const QString &\fBoutput\fP)"
.br
.ti -1c
.RI "virtual void \fBsetVisibility\fP (bool isVisible)"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBanswerInvalid\fP ()"
.br
.RI "\fIanswerInvalid \fP"
.ti -1c
.RI "void \fBanswerValid\fP ()"
.br
.RI "\fIanswerValid \fP"
.ti -1c
.RI "void \fBgoNext\fP ()"
.br
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBresendInput\fP (QVariant \fBinput\fP)"
.br
.ti -1c
.RI "void \fBsendOutput\fP (QVariant \fBoutput\fP)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSH_DecimalQuestionState\fP (QString question, QString \fBname\fP, qreal \fBmin\fP=0, qreal \fBmax\fP=-1, \fBQState\fP *parent=0)"
.br
.ti -1c
.RI "bool \fBcheckValidity\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP (bool canDisplay)"
.br
.ti -1c
.RI "virtual QVariant \fBgivenAnswer\fP () const "
.br
.ti -1c
.RI "virtual QVariant \fBinput\fP () const "
.br
.ti -1c
.RI "virtual bool \fBisAnswerValid\fP (const QVariant &\fBgivenAnswer\fP)"
.br
.ti -1c
.RI "bool \fBisRunning\fP ()"
.br
.ti -1c
.RI "qreal \fBmax\fP () const "
.br
.ti -1c
.RI "qreal \fBmin\fP () const "
.br
.ti -1c
.RI "void \fBonExit\fP (QEvent *event)"
.br
.ti -1c
.RI "virtual QString \fBoutput\fP () const "
.br
.ti -1c
.RI "virtual QVariant \fBrawInput\fP () const "
.br
.ti -1c
.RI "virtual void \fBsetGivenAnswer\fP (const QVariant &\fBgivenAnswer\fP)"
.br
.ti -1c
.RI "virtual void \fBsetInput\fP (const QVariant &\fBinput\fP)"
.br
.ti -1c
.RI "void \fBsetMax\fP (const qreal &\fBmax\fP)"
.br
.ti -1c
.RI "void \fBsetMin\fP (const qreal &\fBmin\fP)"
.br
.ti -1c
.RI "QString \fBtoString\fP ()"
.br
.ti -1c
.RI "bool \fBvisibility\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void \fBonEntry\fP (QEvent *event)"
.br
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "qreal \fBm_max\fP"
.br
.RI "\fIm_max \fP"
.ti -1c
.RI "qreal \fBm_min\fP"
.br
.RI "\fIm_min \fP"
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 11 du fichier SH_DecimalQuestionState\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "SH_DecimalQuestionState::SH_DecimalQuestionState (QStringquestion, QStringname, qrealmin = \fC0\fP, qrealmax = \fC-1\fP, \fBQState\fP *parent = \fC0\fP)"

.PP
Définition à la ligne 10 du fichier SH_DecimalQuestionState\&.cpp\&.
.PP
.nf
10                                                                                                                      :
11     SH_QuestionState(question, name, parent), m_min(min), m_max(max)
12 {
13 
14 }
.fi
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_QuestionState::answerInvalid ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
answerInvalid 
.PP
Référencé par SH_QuestionState::checkValidity(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "void SH_QuestionState::answerValid ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
answerValid 
.PP
Référencé par SH_QuestionState::checkValidity(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "SH_QuestionState::checkValidity ()\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne 20 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::answerInvalid(), SH_QuestionState::answerValid(), SH_QuestionState::givenAnswer(), SH_GenericState::goNext(), SH_QuestionState::isAnswerValid(), et SH_InOutState::setInput()\&.
.PP
Référencé par SH_QuestionState::setGivenAnswer()\&.
.PP
.nf
21 {
22     bool ok = this->isAnswerValid(this->givenAnswer());
23     if(ok) {
24         qDebug() << this->givenAnswer() << " answer valid !";
25         qDebug() << this->givenAnswer();
26         SH_InOutState::setInput(this->givenAnswer());
27         emit answerValid();
28         emit goNext();
29     } else {
30         qDebug() << this->givenAnswer() << " answer invalid :-(";
31         qDebug() << this->givenAnswer();
32         emit answerInvalid();
33     }
34     return ok;
35 }
.fi
.SS "SH_InOutState::display (boolcanDisplay)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIcanDisplay\fP 
.RE
.PP

.PP
Définition à la ligne 101 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_GenericState::isRunning(), SH_InOutState::m_display, SH_InOutState::m_isVisible, SH_InOutState::m_output, et SH_InOutState::sendOutput()\&.
.PP
Référencé par SH_InOutStateMachine::addIOState(), et SH_StatementState::onEntry()\&.
.PP
.nf
102 {
103     if(isRunning()) {
104         m_display=canDisplay;
105         if(m_display && !m_output\&.isEmpty() && m_isVisible) {
106             qDebug() << "resalut !" << QVariant(m_output);
107             emit sendOutput(QVariant(m_output));
108         }
109     }
110 }
.fi
.SS "SH_QuestionState::givenAnswer () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QVariant 
.RE
.PP

.PP
Définition à la ligne 55 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::m_givenAnswer\&.
.PP
Référencé par SH_QuestionState::checkValidity(), SH_DatabaseContentQuestionState::rawInput(), et SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.PP
.nf
56 {
57     return this->m_givenAnswer;
58 }
.fi
.SS "SH_GenericState::goNext ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_QuestionState::checkValidity(), SH_ConfirmationState::confirmInput(), SH_AdaptDatabaseState::insertUpdate(), SH_StatementState::onEntry(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), SH_GenericState::SH_GenericState(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "SH_InOutState::input () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QVariant 
.RE
.PP

.PP
Définition à la ligne 20 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_input\&.
.PP
Référencé par SH_InOutState::rawInput(), SH_DateQuestionState::rawInput(), et SH_InOutState::setInput()\&.
.PP
.nf
21 {
22     return m_input;
23 }
.fi
.SS "SH_DecimalQuestionState::isAnswerValid (const QVariant &givenAnswer)\fC [virtual]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIgivenAnswer\fP 
.RE
.PP

.PP
Implémente \fBSH_QuestionState\fP\&.
.PP
Définition à la ligne 22 du fichier SH_DecimalQuestionState\&.cpp\&.
.PP
Références m_max, et m_min\&.
.PP
.nf
23 {
24     bool ok;
25     qreal answer = givenAnswer\&.toReal(&ok);
26     if(ok) {
27         return ((m_max <= m_min || answer <= m_max) && answer >= m_min);
28     } else {
29         return false;
30     }
31 }
.fi
.SS "SH_GenericState::isRunning ()\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne 92 du fichier SH_GenericDebugableState\&.cpp\&.
.PP
Références SH_GenericState::m_isRunning\&.
.PP
Référencé par SH_InOutStateMachine::addChildrenReplaceTransition(), SH_InOutState::display(), SH_GenericState::emitGoNext(), SH_InOutState::setInput(), SH_InOutState::setOutput(), et SH_InOutState::setVisibility()\&.
.PP
.nf
93 {
94     return m_isRunning;
95 }
.fi
.SS "SH_DecimalQuestionState::max () const"

.PP
\fBRenvoie:\fP
.RS 4
qreal 
.RE
.PP

.PP
Définition à la ligne 61 du fichier SH_DecimalQuestionState\&.cpp\&.
.PP
Références m_max\&.
.PP
Référencé par setMax()\&.
.PP
.nf
62 {
63     return m_max;
64 }
.fi
.SS "SH_DecimalQuestionState::min () const"

.PP
\fBRenvoie:\fP
.RS 4
qreal 
.RE
.PP

.PP
Définition à la ligne 39 du fichier SH_DecimalQuestionState\&.cpp\&.
.PP
Références m_min\&.
.PP
Référencé par setMin()\&.
.PP
.nf
40 {
41     return m_min;
42 }
.fi
.SS "SH_GenericState::next ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_GenericState::emitGoNext()\&.
.SS "SH_GenericState::onEntry (QEvent *event)\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIevent\fP 
.RE
.PP

.PP
Définition à la ligne 71 du fichier SH_GenericDebugableState\&.cpp\&.
.PP
Références SH_GenericState::m_isRunning, et SH_NamedObject::name()\&.
.PP
Référencé par SH_StatementState::onEntry()\&.
.PP
.nf
72 {
73     Q_UNUSED(event);
74     m_isRunning = true;
75     this->blockSignals(!m_isRunning);
76     qDebug() << "Machine: " << machine()->objectName() << " entered " << name();
77 }
.fi
.SS "SH_InOutState::onExit (QEvent *event)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIevent\fP 
.RE
.PP

.PP
Définition à la ligne 118 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_input, SH_InOutState::m_isVisible, SH_GenericState::onExit(), et SH_InOutState::resendInput()\&.
.PP
.nf
119 {
120     if(m_isVisible) {
121         emit resendInput(m_input);
122     }
123     SH_GenericState::onExit(event);
124 }
.fi
.SS "SH_InOutState::output () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 58 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_output\&.
.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutState::setOutput(), et SH_StatementState::SH_StatementState()\&.
.PP
.nf
59 {
60     return m_output;
61 }
.fi
.SS "SH_InOutState::rawInput () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QVariant 
.RE
.PP

.PP
Réimplémentée dans \fBSH_DateQuestionState\fP, et \fBSH_DatabaseContentQuestionState\fP\&.
.PP
Définition à la ligne 30 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::input()\&.
.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.PP
.nf
31 {
32     return input();
33 }
.fi
.SS "SH_InOutState::resendInput (QVariantinput)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIinput\fP 
.RE
.PP

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutState::onExit(), et SH_InOutState::setInput()\&.
.SS "SH_InOutState::sendOutput (QVariantoutput)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIoutput\fP 
.RE
.PP

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutState::display(), et SH_InOutState::setOutput()\&.
.SS "SH_QuestionState::setGivenAnswer (const QVariant &givenAnswer)\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIgivenAnswer\fP 
.RE
.PP

.PP
Définition à la ligne 66 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::checkValidity(), et SH_QuestionState::m_givenAnswer\&.
.PP
Référencé par SH_QuestionState::setInput()\&.
.PP
.nf
67 {
68     this->m_givenAnswer = givenAsnwer;
69     this->checkValidity();
70 }
.fi
.SS "SH_QuestionState::setInput (const QVariant &input)\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIinput\fP 
.RE
.PP

.PP
Réimplémentée à partir de \fBSH_InOutState\fP\&.
.PP
Définition à la ligne 43 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::setGivenAnswer()\&.
.PP
Référencé par SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
44 {
45     qDebug() << "new answer " << input\&.toString();
46     this->setGivenAnswer(input);
47 }
.fi
.SS "SH_DecimalQuestionState::setMax (const qreal &max)"

.PP
\fBParamètres:\fP
.RS 4
\fImax\fP 
.RE
.PP

.PP
Définition à la ligne 72 du fichier SH_DecimalQuestionState\&.cpp\&.
.PP
Références m_max, et max()\&.
.PP
.nf
73 {
74     m_max = max;
75 }
.fi
.SS "SH_DecimalQuestionState::setMin (const qreal &min)"

.PP
\fBParamètres:\fP
.RS 4
\fImin\fP 
.RE
.PP

.PP
Définition à la ligne 50 du fichier SH_DecimalQuestionState\&.cpp\&.
.PP
Références m_min, et min()\&.
.PP
.nf
51 {
52     m_min = min;
53 }
.fi
.SS "SH_InOutState::setOutput (const QString &output)\fC [virtual]\fP, \fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIoutput\fP 
.RE
.PP

.PP
Réimplémentée dans \fBSH_DatabaseContentQuestionState\fP\&.
.PP
Définition à la ligne 70 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_GenericState::isRunning(), SH_InOutState::m_isVisible, SH_InOutState::m_output, SH_InOutState::output(), et SH_InOutState::sendOutput()\&.
.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_DatabaseContentQuestionState::setOutput(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
71 {
72     if(isRunning()) {
73         m_output = output;
74         if(m_isVisible) {
75             emit sendOutput(QVariant(m_output));
76         }
77     }
78 }
.fi
.SS "SH_InOutState::setVisibility (boolisVisible)\fC [virtual]\fP, \fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIisVisible\fP 
.RE
.PP

.PP
Définition à la ligne 85 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_GenericState::isRunning(), et SH_InOutState::m_isVisible\&.
.PP
Référencé par SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
86 {
87     if(isRunning()) {
88         m_isVisible = isVisible;
89     }
90 }
.fi
.SS "SH_GenericState::toString ()\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Réimplémentée à partir de \fBSH_NamedObject\fP\&.
.PP
Définition à la ligne 22 du fichier SH_GenericDebugableState\&.cpp\&.
.PP
Références SH_GenericStateMachine::toString(), et SH_NamedObject::toString()\&.
.PP
Référencé par SH_GenericStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addIOState(), SH_DateQuestionState::rawInput(), et SH_GenericStateMachine::toString()\&.
.PP
.nf
23 {
24     QStateMachine* machine = this->machine();
25     SH_InOutStateMachine* mach = qobject_cast<SH_InOutStateMachine *>(machine);
26     if(mach) {
27         return SH_NamedObject::toString()+ " [in "+mach->toString()+"] ";
28     } else {
29         return SH_NamedObject::toString();
30     }
31 }
.fi
.SS "SH_InOutState::visibility ()\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne 97 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_isVisible\&.
.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.PP
.nf
97                                {
98     return m_isVisible;
99 }
.fi
.SH "Documentation des données membres"
.PP 
.SS "qreal SH_DecimalQuestionState::m_max\fC [private]\fP"

.PP
m_max 
.PP
Définition à la ligne 76 du fichier SH_DecimalQuestionState\&.h\&.
.PP
Référencé par isAnswerValid(), max(), et setMax()\&.
.SS "qreal SH_DecimalQuestionState::m_min\fC [private]\fP"

.PP
m_min 
.PP
Définition à la ligne 72 du fichier SH_DecimalQuestionState\&.h\&.
.PP
Référencé par isAnswerValid(), min(), et setMin()\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
