.TH "SH_DataDelegate" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_DataDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBButton\fP\&.
.PP
Dérivée par \fBSH_BillingsDelegate\fP, \fBSH_BookingsDelegate\fP, \fBSH_RoomsDelegate\fP, \fBSH_ServicesDelegate\fP, et \fBSH_VATDelegate\fP\&.
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBfontSize\fP"
.br
.ti -1c
.RI "string \fBvalue\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_DataDelegate\&.qml\&.
.SH "Documentation des propriétés"
.PP 
.SS "int SH_DataDelegate::fontSize"

.PP
Définition à la ligne 9 du fichier SH_DataDelegate\&.qml\&.
.SS "string SH_DataDelegate::value"

.PP
Définition à la ligne 7 du fichier SH_DataDelegate\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
