.TH "models/SH_ExtendedSqlProxyModel.h" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models/SH_ExtendedSqlProxyModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QSortFilterProxyModel>\fP
.br
\fC#include 'SH_SqlDataModel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSH_ExtendedProxyModel\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
