.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_ExtendedSqlProxyModel.cpp" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_ExtendedSqlProxyModel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtSql/QSqlRecord>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'SH_ExtendedSqlProxyModel\&.h'\fP
.br
\fC#include 'SH_MessageManager\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
