.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/views/SH_ExtendedQQmlAction.h" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/views/SH_ExtendedQQmlAction.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtCore/QUrl>\fP
.br
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtGui/QIcon>\fP
.br
\fC#include <QtGui/QKeySequence>\fP
.br
\fC#include <QtCore/qpointer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSH_ExtendedQQmlAction\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
