.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/views/SH_ExtendedQQmlAction.cpp" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/views/SH_ExtendedQQmlAction.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui/QGuiApplication>\fP
.br
\fC#include <QtQuick/QQuickItem>\fP
.br
\fC#include <QtQuick/QQuickWindow>\fP
.br
\fC#include <QQmlFile>\fP
.br
\fC#include 'SH_ExtendedQQmlAction\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "bool \fBqShortcutContextMatcher\fP (\fBQObject\fP *o, Qt::ShortcutContext context)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "bool qShortcutContextMatcher (\fBQObject\fP *o, Qt::ShortcutContextcontext)"

.PP
Définition à la ligne 50 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
.nf
51 {
52     switch (context) {
53     case Qt::ApplicationShortcut:
54         return true;
55     case Qt::WindowShortcut: {
56         QObject *w = o;
57         while (w && !w->isWindowType()) {
58             w = w->parent();
59             if (QQuickItem * item = qobject_cast<QQuickItem*>(w))
60                 w = item->window();
61         }
62         if (w && w == QGuiApplication::focusWindow())
63             return true;
64     }
65     case Qt::WidgetShortcut:
66     case Qt::WidgetWithChildrenShortcut:
67         break;
68     }
69 
70     return false;
71 }
.fi
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
