.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_ExtendedProxyModel.cpp" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_ExtendedProxyModel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtSql/QSqlRecord>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'SH_ExtendedSqlProxyModel\&.h'\fP
.br
\fC#include 'SH_MessageManager\&.h'\fP
.br

.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBSimpleHotel\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
