.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/views/SH_ExtendedQQmlAction.cpp" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/views/SH_ExtendedQQmlAction.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui/QGuiApplication>\fP
.br
\fC#include <QtQuick/QQuickItem>\fP
.br
\fC#include <QtQuick/QQuickWindow>\fP
.br
\fC#include <QQmlFile>\fP
.br
\fC#include 'SH_ExtendedQQmlAction\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "bool \fBqShortcutContextMatcher\fP (\fBQObject\fP *o, Qt::ShortcutContext context)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "bool qShortcutContextMatcher (\fBQObject\fP *o, Qt::ShortcutContextcontext)"

.PP
Définition à la ligne 42 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
.nf
43 {
44     switch (context) {
45     case Qt::ApplicationShortcut:
46     return true;
47     case Qt::WindowShortcut: {
48     QObject *w = o;
49     while (w && !w->isWindowType()) {
50     w = w->parent();
51     if (QQuickItem * item = qobject_cast<QQuickItem*>(w))
52     w = item->window();
53     }
54     if (w && w == QGuiApplication::focusWindow())
55     return true;
56     }
57     case Qt::WidgetShortcut:
58     case Qt::WidgetWithChildrenShortcut:
59     break;
60     }
61     return false;
62 }
.fi
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
