.TH "SH_ExtendedQQmlAction" 3 "Lundi Juin 24 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_ExtendedQQmlAction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_ExtendedQQmlAction\&.h>\fP
.PP
Est dérivée de \fBQObject\fP\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBtrigger\fP ()"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBenabledChanged\fP ()"
.br
.ti -1c
.RI "void \fBiconChanged\fP ()"
.br
.ti -1c
.RI "void \fBiconNameChanged\fP ()"
.br
.ti -1c
.RI "void \fBiconSourceChanged\fP ()"
.br
.ti -1c
.RI "void \fBkeyShortcutChanged\fP (Qt::Key \fBkeyShortcut\fP)"
.br
.ti -1c
.RI "void \fBshortcutChanged\fP (QString \fBshortcut\fP)"
.br
.ti -1c
.RI "void \fBtextChanged\fP ()"
.br
.ti -1c
.RI "void \fBtoggled\fP (bool checked)"
.br
.ti -1c
.RI "void \fBtooltipChanged\fP (QString arg)"
.br
.ti -1c
.RI "void \fBtriggered\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSH_ExtendedQQmlAction\fP (\fBQObject\fP *parent=0)"
.br
.ti -1c
.RI "\fB~SH_ExtendedQQmlAction\fP ()"
.br
.ti -1c
.RI "bool \fBevent\fP (QEvent *e)"
.br
.ti -1c
.RI "QIcon \fBicon\fP () const "
.br
.ti -1c
.RI "QString \fBiconName\fP () const "
.br
.ti -1c
.RI "QUrl \fBiconSource\fP () const "
.br
.ti -1c
.RI "QVariant \fBiconVariant\fP () const "
.br
.ti -1c
.RI "bool \fBisEnabled\fP () const "
.br
.ti -1c
.RI "QKeySequence \fBkeyShortcut\fP () const "
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool e)"
.br
.ti -1c
.RI "void \fBsetIcon\fP (QIcon \fBicon\fP)"
.br
.ti -1c
.RI "void \fBsetIconName\fP (const QString &\fBiconName\fP)"
.br
.ti -1c
.RI "void \fBsetIconSource\fP (const QUrl &\fBiconSource\fP)"
.br
.ti -1c
.RI "void \fBsetKeyShortcut\fP (const Qt::Key &\fBshortcut\fP)"
.br
.ti -1c
.RI "void \fBsetMnemonicFromText\fP (const QString &mnemonic)"
.br
.ti -1c
.RI "void \fBsetShortcut\fP (const QString &\fBshortcut\fP)"
.br
.ti -1c
.RI "void \fBsetText\fP (const QString &\fBtext\fP)"
.br
.ti -1c
.RI "void \fBsetTooltip\fP (const QString &\fBtooltip\fP)"
.br
.ti -1c
.RI "QString \fBshortcut\fP () const "
.br
.ti -1c
.RI "QString \fBtext\fP () const "
.br
.ti -1c
.RI "QString \fBtooltip\fP () const "
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void \fBsetKeySequence\fP (const QKeySequence &sequence)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "QVariant \fB__icon\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP"
.br
.ti -1c
.RI "QString \fBiconName\fP"
.br
.ti -1c
.RI "QUrl \fBiconSource\fP"
.br
.ti -1c
.RI "Qt::Key \fBkeyShortcut\fP"
.br
.ti -1c
.RI "QString \fBshortcut\fP"
.br
.ti -1c
.RI "QString \fBtext\fP"
.br
.ti -1c
.RI "QString \fBtooltip\fP"
.br
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "bool \fBm_enabled\fP"
.br
.RI "\fIm_enabled \fP"
.ti -1c
.RI "QIcon \fBm_icon\fP"
.br
.RI "\fIm_icon \fP"
.ti -1c
.RI "QString \fBm_iconName\fP"
.br
.RI "\fIm_iconName \fP"
.ti -1c
.RI "QUrl \fBm_iconSource\fP"
.br
.RI "\fIm_iconSource \fP"
.ti -1c
.RI "QKeySequence \fBm_mnemonic\fP"
.br
.RI "\fIm_mnemonic \fP"
.ti -1c
.RI "QKeySequence \fBm_shortcut\fP"
.br
.RI "\fIm_shortcut \fP"
.ti -1c
.RI "QString \fBm_text\fP"
.br
.RI "\fIm_text \fP"
.ti -1c
.RI "QString \fBm_tooltip\fP"
.br
.RI "\fIm_tooltip \fP"
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier SH_ExtendedQQmlAction\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "SH_ExtendedQQmlAction::SH_ExtendedQQmlAction (\fBQObject\fP *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Définition à la ligne 14 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
.nf
15     : QObject(parent)
16     , m_enabled(true)
17 {
18 }
.fi
.SS "SH_ExtendedQQmlAction::~SH_ExtendedQQmlAction ()"

.PP
Définition à la ligne 25 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références setKeyShortcut(), et setMnemonicFromText()\&.
.PP
.nf
26 {
27     setKeyShortcut(Qt::Key_unknown);
28     setMnemonicFromText(QString());
29 }
.fi
.SH "Documentation des fonctions membres"
.PP 
.SS "SH_ExtendedQQmlAction::enabledChanged ()\fC [signal]\fP"

.PP
Référencé par setEnabled()\&.
.SS "SH_ExtendedQQmlAction::event (QEvent *e)"

.PP
\fBParamètres:\fP
.RS 4
\fIe\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne 228 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références m_enabled, m_mnemonic, m_shortcut, et trigger()\&.
.PP
.nf
229 {
230     if (!m_enabled)
231         return false;
232 
233     if (e->type() != QEvent::Shortcut)
234         return false;
235 
236     QShortcutEvent *se = static_cast<QShortcutEvent *>(e);
237 
238     Q_ASSERT_X(se->key() == m_shortcut || se->key() == m_mnemonic,
239                "QQQuickAction::event",
240                "Received shortcut event from incorrect shortcut");
241     if (se->isAmbiguous()) {
242         qWarning("QQQuickAction::event: Ambiguous shortcut overload: %s", se->key()\&.toString(QKeySequence::NativeText)\&.toLatin1()\&.constData());
243         return false;
244     }
245 
246     trigger();
247 
248     return true;
249 }
.fi
.SS "SH_ExtendedQQmlAction::icon () const\fC [inline]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QIcon 
.RE
.PP

.PP
Définition à la ligne 166 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références m_icon\&.
.PP
Référencé par setIcon()\&.
.PP
.nf
166 { return m_icon; }
.fi
.SS "SH_ExtendedQQmlAction::iconChanged ()\fC [signal]\fP"

.PP
Référencé par setIcon(), setIconName(), et setIconSource()\&.
.SS "QString SH_ExtendedQQmlAction::iconName () const"

.PP
Référencé par setIconName()\&.
.SS "SH_ExtendedQQmlAction::iconNameChanged ()\fC [signal]\fP"

.PP
Référencé par setIconName()\&.
.SS "QUrl SH_ExtendedQQmlAction::iconSource () const\fC [inline]\fP"

.PP
Définition à la ligne 121 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références m_iconSource\&.
.PP
Référencé par setIconSource()\&.
.PP
.nf
121 { return m_iconSource; }
.fi
.SS "SH_ExtendedQQmlAction::iconSourceChanged ()\fC [signal]\fP"

.PP
Référencé par setIconSource()\&.
.SS "SH_ExtendedQQmlAction::iconVariant () const\fC [inline]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QVariant 
.RE
.PP

.PP
Définition à la ligne 173 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références m_icon\&.
.PP
.nf
173 { return QVariant(m_icon); }
.fi
.SS "SH_ExtendedQQmlAction::isEnabled () const\fC [inline]\fP"

.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne 151 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références m_enabled\&.
.PP
.nf
151 { return m_enabled; }
.fi
.SS "QKeySequence SH_ExtendedQQmlAction::keyShortcut () const\fC [inline]\fP"

.PP
Définition à la ligne 83 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références m_shortcut\&.
.PP
.nf
83 { return m_shortcut; }
.fi
.SS "SH_ExtendedQQmlAction::keyShortcutChanged (Qt::KeykeyShortcut)\fC [signal]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIkeyShortcut\fP 
.RE
.PP

.SS "SH_ExtendedQQmlAction::setEnabled (boole)"

.PP
\fBParamètres:\fP
.RS 4
\fIe\fP 
.RE
.PP

.PP
Définition à la ligne 212 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références enabledChanged(), et m_enabled\&.
.PP
.nf
213 {
214     if (e == m_enabled)
215         return;
216     m_enabled = e;
217     emit enabledChanged();
218 }
.fi
.SS "SH_ExtendedQQmlAction::setIcon (QIconicon)\fC [inline]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIicon\fP 
.RE
.PP

.PP
Définition à la ligne 180 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références icon(), iconChanged(), et m_icon\&.
.PP
.nf
180 { m_icon = icon; emit iconChanged(); }
.fi
.SS "SH_ExtendedQQmlAction::setIconName (const QString &iconName)"

.PP
\fBParamètres:\fP
.RS 4
\fIiconName\fP 
.RE
.PP

.PP
Définition à la ligne 184 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références iconChanged(), iconName(), iconNameChanged(), m_icon, m_iconName, et m_iconSource\&.
.PP
.nf
185 {
186     if (iconName == m_iconName)
187         return;
188     m_iconName = iconName;
189     m_icon = QIcon::fromTheme(m_iconName, QIcon(QQmlFile::urlToLocalFileOrQrc(m_iconSource)));
190     emit iconNameChanged();
191     emit iconChanged();
192 }
.fi
.SS "SH_ExtendedQQmlAction::setIconSource (const QUrl &iconSource)"

.PP
\fBParamètres:\fP
.RS 4
\fIiconSource\fP 
.RE
.PP

.PP
Définition à la ligne 154 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références iconChanged(), iconSource(), iconSourceChanged(), m_icon, m_iconName, et m_iconSource\&.
.PP
.nf
155 {
156     if (iconSource == m_iconSource)
157         return;
158 
159     m_iconSource = iconSource;
160     if (m_iconName\&.isEmpty() || m_icon\&.isNull()) {
161         QString fileString = QQmlFile::urlToLocalFileOrQrc(iconSource);
162         m_icon = QIcon(fileString);
163 
164         emit iconChanged();
165     }
166     emit iconSourceChanged();
167 }
.fi
.SS "SH_ExtendedQQmlAction::setKeySequence (const QKeySequence &sequence)\fC [protected]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIsequence\fP 
.RE
.PP

.PP
Définition à la ligne 78 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références m_shortcut, shortcut(), et shortcutChanged()\&.
.PP
Référencé par setKeyShortcut(), et setShortcut()\&.
.PP
.nf
78                                                                        {
79     if (sequence == m_shortcut)
80         return;
81 
82     /*if (!m_shortcut\&.isEmpty())
83         QGuiApplicationPrivate::instance()->shortcutMap\&.removeShortcut(0, this, m_shortcut);
84     */
85     m_shortcut = sequence;
86 
87     if (!m_shortcut\&.isEmpty()) {
88         Qt::ShortcutContext context = Qt::WindowShortcut;
89         /*QGuiApplicationPrivate::instance()->shortcutMap\&.addShortcut(this, m_shortcut, context, qShortcutContextMatcher);*/
90     }
91     emit shortcutChanged(shortcut());
92 }
.fi
.SS "SH_ExtendedQQmlAction::setKeyShortcut (const Qt::Key &shortcut)"

.PP
\fBParamètres:\fP
.RS 4
\fIshortcut\fP 
.RE
.PP

.PP
Définition à la ligne 99 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références setKeySequence()\&.
.PP
Référencé par ~SH_ExtendedQQmlAction()\&.
.PP
.nf
100 {
101     setKeySequence(QKeySequence(shortcut));
102 }
.fi
.SS "SH_ExtendedQQmlAction::setMnemonicFromText (const QString &mnemonic)"

.PP
\fBParamètres:\fP
.RS 4
\fImnemonic\fP 
.RE
.PP

.PP
Définition à la ligne 132 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références m_mnemonic\&.
.PP
Référencé par setText(), et ~SH_ExtendedQQmlAction()\&.
.PP
.nf
133 {
134     QKeySequence sequence = QKeySequence::mnemonic(text);
135     if (m_mnemonic == sequence)
136         return;
137 
138     /*if (!m_mnemonic\&.isEmpty())
139         QGuiApplicationPrivate::instance()->shortcutMap\&.removeShortcut(0, this, m_mnemonic);
140     */
141     m_mnemonic = sequence;
142 
143     if (!m_mnemonic\&.isEmpty()) {
144         Qt::ShortcutContext context = Qt::WindowShortcut;
145         /*QGuiApplicationPrivate::instance()->shortcutMap\&.addShortcut(this, m_mnemonic, context, qShortcutContextMatcher);*/
146     }
147 }
.fi
.SS "SH_ExtendedQQmlAction::setShortcut (const QString &shortcut)"

.PP
\fBParamètres:\fP
.RS 4
\fIshortcut\fP 
.RE
.PP

.PP
Définition à la ligne 119 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références setKeySequence(), et shortcut()\&.
.PP
.nf
120 {
121     if(shortcut() == arg)
122         return;
123 
124     setKeySequence(QKeySequence::fromString(arg));
125 }
.fi
.SS "SH_ExtendedQQmlAction::setText (const QString &text)"

.PP
\fBParamètres:\fP
.RS 4
\fItext\fP 
.RE
.PP

.PP
Définition à la ligne 36 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références m_text, setMnemonicFromText(), text(), et textChanged()\&.
.PP
.nf
37 {
38     if (text == m_text)
39         return;
40     m_text = text;
41     setMnemonicFromText(m_text);
42     emit textChanged();
43 }
.fi
.SS "SH_ExtendedQQmlAction::setTooltip (const QString &tooltip)"

.PP
\fBParamètres:\fP
.RS 4
\fItooltip\fP 
.RE
.PP

.PP
Définition à la ligne 199 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références m_tooltip, et tooltipChanged()\&.
.PP
.nf
200 {
201     if (m_tooltip != arg) {
202         m_tooltip = arg;
203         emit tooltipChanged(arg);
204     }
205 }
.fi
.SS "QString SH_ExtendedQQmlAction::shortcut () const"

.PP
Référencé par setKeySequence(), et setShortcut()\&.
.SS "SH_ExtendedQQmlAction::shortcutChanged (QStringshortcut)\fC [signal]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIshortcut\fP 
.RE
.PP

.PP
Référencé par setKeySequence()\&.
.SS "QString SH_ExtendedQQmlAction::text () const\fC [inline]\fP"

.PP
Définition à la ligne 53 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références m_text\&.
.PP
Référencé par setText()\&.
.PP
.nf
53 { return m_text; }
.fi
.SS "SH_ExtendedQQmlAction::textChanged ()\fC [signal]\fP"

.PP
Référencé par setText()\&.
.SS "SH_ExtendedQQmlAction::toggled (boolchecked)\fC [signal]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIchecked\fP 
.RE
.PP

.SS "QString SH_ExtendedQQmlAction::tooltip () const\fC [inline]\fP"

.PP
Définition à la ligne 136 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Références m_tooltip\&.
.PP
.nf
136 { return m_tooltip; }
.fi
.SS "SH_ExtendedQQmlAction::tooltipChanged (QStringarg)\fC [signal]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIarg\fP 
.RE
.PP

.PP
Référencé par setTooltip()\&.
.SS "SH_ExtendedQQmlAction::trigger ()\fC [slot]\fP"

.PP
Définition à la ligne 256 du fichier SH_ExtendedQQmlAction\&.cpp\&.
.PP
Références m_enabled, et triggered()\&.
.PP
Référencé par event()\&.
.PP
.nf
257 {
258     if (!m_enabled)
259         return;
260     emit triggered();
261 }
.fi
.SS "SH_ExtendedQQmlAction::triggered ()\fC [signal]\fP"

.PP
Référencé par trigger()\&.
.SH "Documentation des données membres"
.PP 
.SS "bool SH_ExtendedQQmlAction::m_enabled\fC [private]\fP"

.PP
m_enabled 
.PP
Définition à la ligne 297 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par event(), isEnabled(), setEnabled(), et trigger()\&.
.SS "QIcon SH_ExtendedQQmlAction::m_icon\fC [private]\fP"

.PP
m_icon 
.PP
Définition à la ligne 293 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par icon(), iconVariant(), setIcon(), setIconName(), et setIconSource()\&.
.SS "QString SH_ExtendedQQmlAction::m_iconName\fC [private]\fP"

.PP
m_iconName 
.PP
Définition à la ligne 289 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par setIconName(), et setIconSource()\&.
.SS "QUrl SH_ExtendedQQmlAction::m_iconSource\fC [private]\fP"

.PP
m_iconSource 
.PP
Définition à la ligne 285 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par iconSource(), setIconName(), et setIconSource()\&.
.SS "QKeySequence SH_ExtendedQQmlAction::m_mnemonic\fC [private]\fP"

.PP
m_mnemonic 
.PP
Définition à la ligne 305 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par event(), et setMnemonicFromText()\&.
.SS "QKeySequence SH_ExtendedQQmlAction::m_shortcut\fC [private]\fP"

.PP
m_shortcut 
.PP
Définition à la ligne 301 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par event(), keyShortcut(), et setKeySequence()\&.
.SS "QString SH_ExtendedQQmlAction::m_text\fC [private]\fP"

.PP
m_text 
.PP
Définition à la ligne 281 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par setText(), et text()\&.
.SS "QString SH_ExtendedQQmlAction::m_tooltip\fC [private]\fP"

.PP
m_tooltip 
.PP
Définition à la ligne 309 du fichier SH_ExtendedQQmlAction\&.h\&.
.PP
Référencé par setTooltip(), et tooltip()\&.
.SH "Documentation des propriétés"
.PP 
.SS "QVariant SH_ExtendedQQmlAction::__icon\fC [read]\fP"

.PP
Définition à la ligne 23 du fichier SH_ExtendedQQmlAction\&.h\&.
.SS "bool SH_ExtendedQQmlAction::enabled\fC [read]\fP, \fC [write]\fP"

.PP
Définition à la ligne 25 du fichier SH_ExtendedQQmlAction\&.h\&.
.SS "SH_ExtendedQQmlAction::iconName\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 22 du fichier SH_ExtendedQQmlAction\&.h\&.
.SS "SH_ExtendedQQmlAction::iconSource\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QUrl 
.RE
.PP

.PP
Définition à la ligne 21 du fichier SH_ExtendedQQmlAction\&.h\&.
.SS "SH_ExtendedQQmlAction::keyShortcut\fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QKeySequence 
.RE
.PP

.PP
Définition à la ligne 29 du fichier SH_ExtendedQQmlAction\&.h\&.
.SS "SH_ExtendedQQmlAction::shortcut\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 28 du fichier SH_ExtendedQQmlAction\&.h\&.
.SS "SH_ExtendedQQmlAction::text\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 20 du fichier SH_ExtendedQQmlAction\&.h\&.
.SS "SH_ExtendedQQmlAction::tooltip\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 24 du fichier SH_ExtendedQQmlAction\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
