.TH "SH_HeaderView" 3 "Lundi Juin 24 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_HeaderView \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBGridLayout\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBchecked\fP (int index, bool ch)"
.br
.ti -1c
.RI "void \fBup\fP (int index)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "var \fBdelegateModel\fP"
.br
.ti -1c
.RI "alias \fBmodel\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_HeaderView\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_HeaderView::checked (intindex, boolch)\fC [signal]\fP"

.SS "void SH_HeaderView::up (intindex)\fC [signal]\fP"

.SH "Documentation des propriétés"
.PP 
.SS "var SH_HeaderView::delegateModel"

.PP
Définition à la ligne 7 du fichier SH_HeaderView\&.qml\&.
.SS "alias SH_HeaderView::model"

.PP
Définition à la ligne 9 du fichier SH_HeaderView\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
