.TH "Sh_LoopingInOutStateMachine" 3 "Lundi Juin 24 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sh_LoopingInOutStateMachine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_LoopingIOStateMachine\&.h>\fP
.PP
Est dérivée de \fBSH_InOutStateMachine\fP\&.
.PP
Dérivée par \fBSH_ServiceCharging\fP\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBaddIOState\fP (\fBSH_InOutState\fP *state, QString field)"
.br
.ti -1c
.RI "void \fBaddIOStateMachine\fP (\fBSH_InOutStateMachine\fP *fsm)"
.br
.ti -1c
.RI "bool \fBemitNext\fP ()"
.br
.ti -1c
.RI "void \fBsetContentValue\fP (QVariant content, QString field)"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBcancelReplacement\fP ()"
.br
.ti -1c
.RI "void \fBclearAll\fP ()"
.br
.ti -1c
.RI "void \fBconfirmInput\fP ()"
.br
.ti -1c
.RI "void \fBdisplayCalendar\fP ()"
.br
.ti -1c
.RI "void \fBdisplayFileDialog\fP ()"
.br
.ti -1c
.RI "void \fBlimitChanged\fP ()"
.br
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBreceiveInput\fP (QString input)"
.br
.ti -1c
.RI "void \fBreplaceInput\fP (QString field)"
.br
.ti -1c
.RI "void \fBresendText\fP (QString text, bool editable=false)"
.br
.ti -1c
.RI "void \fBsendText\fP (QString text, bool editable=false)"
.br
.ti -1c
.RI "void \fBvalidateInput\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSh_LoopingInOutStateMachine\fP (QString \fBtableName\fP, QString \fBname\fP='looping', int \fBlimit\fP=0, \fBQObject\fP *parent=0)"
.br
.ti -1c
.RI "void \fBaddChildrenNextTransition\fP (QAbstractState *previousState, QAbstractState *nextState)"
.br
.ti -1c
.RI "int \fBcurrent\fP () const "
.br
.ti -1c
.RI "QVariant \fBgetContentValue\fP (QString field)"
.br
.ti -1c
.RI "QHistoryState * \fBhistoryValue\fP (QString field)"
.br
.ti -1c
.RI "QVariantMap \fBioContent\fP () const "
.br
.ti -1c
.RI "int \fBlimit\fP () const "
.br
.ti -1c
.RI "void \fBsetCurrent\fP (int \fBcurrent\fP)"
.br
.ti -1c
.RI "void \fBsetIOcontent\fP (const QVariantMap &\fBioContent\fP)"
.br
.ti -1c
.RI "void \fBsetIOStateHistory\fP (QHistoryState *state, QString field)"
.br
.ti -1c
.RI "void \fBsetLimit\fP (int \fBlimit\fP)"
.br
.ti -1c
.RI "void \fBsetPersistentContentValue\fP (QVariant value, QString field)"
.br
.ti -1c
.RI "void \fBsetTableName\fP (const QString &\fBtableName\fP)"
.br
.ti -1c
.RI "void \fBstopLooping\fP ()"
.br
.ti -1c
.RI "QString \fBtableName\fP () const "
.br
.ti -1c
.RI "QString \fBtoString\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "QMap< QString, QHistoryState * > \fBioStatesHistory\fP () const "
.br
.ti -1c
.RI "bool \fBisERunning\fP ()"
.br
.ti -1c
.RI "void \fBonEntry\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBonExit\fP (QEvent *event)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "QVariantMap \fBm_ioContent\fP"
.br
.RI "\fIm_ioContent \fP"
.ti -1c
.RI "QMap< QString, QHistoryState * > \fBm_ioStatesHistory\fP"
.br
.RI "\fIm_ioStatesHistory \fP"
.ti -1c
.RI "QString \fBm_tableName\fP"
.br
.RI "\fIm_tableName \fP"
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBlimit\fP"
.br
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "QList< QVariantMap > \fBm_contents\fP"
.br
.RI "\fIm_contents \fP"
.ti -1c
.RI "int \fBm_current\fP"
.br
.RI "\fIm_current \fP"
.ti -1c
.RI "int \fBm_limit\fP"
.br
.RI "\fIm_limit \fP"
.ti -1c
.RI "QVariantMap \fBm_persistentContent\fP"
.br
.RI "\fIm_persistentContent \fP"
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 10 du fichier SH_LoopingIOStateMachine\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Sh_LoopingInOutStateMachine::Sh_LoopingInOutStateMachine (QStringtableName, QStringname = \fC'looping'\fP, intlimit = \fC0\fP, \fBQObject\fP *parent = \fC0\fP)"

.PP
Définition à la ligne 10 du fichier SH_LoopingIOStateMachine\&.cpp\&.
.PP
.nf
10                                                                                                                     :
11     SH_InOutStateMachine(tableName, name, parent), m_limit(limit), m_current(-1)
12 {
13 
14 }
.fi
.SH "Documentation des fonctions membres"
.PP 
.SS "Sh_LoopingInOutStateMachine::addChildrenNextTransition (QAbstractState *previousState, QAbstractState *nextState)"

.PP
\fBParamètres:\fP
.RS 4
\fIpreviousState\fP 
.br
\fInextState\fP 
.RE
.PP

.PP
Définition à la ligne 86 du fichier SH_LoopingIOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::historyValue(), SH_AdaptDatabaseState::insertUpdate(), m_contents, m_current, SH_InOutStateMachine::m_ioContent, m_limit, m_persistentContent, SH_InOutStateMachine::m_tableName, SH_InOutStateMachine::next(), SH_InOutStateMachine::replaceInput(), SH_InOutStateMachine::setContentValue(), et SH_InOutStateMachine::toString()\&.
.PP
Référencé par SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
87 {
88     SH_GenericState* genPreviousState = qobject_cast<SH_GenericState*>(previousState);
89     SH_InOutStateMachine* fsmPreviousState = qobject_cast<SH_InOutStateMachine*>(previousState);
90     QFinalState* final = qobject_cast<QFinalState*>(nextState);
91     if(final) {
92         /*à faire au moment de l'entrée dans l'état previousState*/
93         connect(previousState, &QAbstractState::entered, [=]() {
94             m_current++;
95             m_contents\&.append(m_ioContent);
96             m_ioContent\&.clear();
97             m_ioContent = m_persistentContent;
98             if(m_limit == 0 || m_current < m_limit) {
99                 if(genPreviousState) {
100                     connect(genPreviousState, &QAbstractState::entered, [=]() {
101                         genPreviousState->addTransition(genPreviousState, SIGNAL(next()), initialState());
102                     });
103                 }
104                 if(fsmPreviousState) {
105                     connect(fsmPreviousState, &QAbstractState::entered, [=]() {
106                         fsmPreviousState->addTransition(fsmPreviousState, SIGNAL(next()), initialState());
107                     });
108                 }
109             } else {
110                 SH_AdaptDatabaseState* nextSaveState = new SH_AdaptDatabaseState("enregistrement 0 de la machine "+toString());
111                 if(genPreviousState) {
112                     genPreviousState->addTransition(genPreviousState, SIGNAL(next()), nextSaveState);
113                 }
114                 if(fsmPreviousState) {
115                     fsmPreviousState->addTransition(fsmPreviousState, SIGNAL(next()), nextSaveState);
116                 }
117                 if(genPreviousState || fsmPreviousState) {
118                     for(int i = 1; i < m_limit; i++) {
119                         SH_AdaptDatabaseState* saveState = nextSaveState;
120                         nextSaveState = new SH_AdaptDatabaseState(QString("enregistrement %1 de la machine %2")\&.arg(QString::number(i))\&.arg(toString()));
121                         saveState->addTransition(saveState, SIGNAL(next()),nextSaveState);
122                         connect(saveState, &QAbstractState::exited, [=]() {
123                             connect(nextSaveState, &QAbstractState::entered, [=]() {
124                                 setContentValue(nextSaveState->insertUpdate(m_tableName, m_contents[i]), "ID");
125                             });
126                         });
127                     }
128                     nextSaveState->addTransition(nextSaveState, SIGNAL(next()),final);
129                 }
130             }
131         });
132     } else {
133         if(genPreviousState) {
134             genPreviousState->addTransition(genPreviousState, SIGNAL(next()), nextState);
135         }
136         if(fsmPreviousState) {
137             fsmPreviousState->addTransition(fsmPreviousState, SIGNAL(next()), nextState);
138         }
139     }
140     if(genPreviousState) {
141         /*à faire au moment de l'entrée dans l'état previousState*/
142         connect(genPreviousState, &QAbstractState::entered, [=]() {
143             connect(this, &SH_InOutStateMachine::replaceInput, [=](QString field) {
144                 /*après avoir demandé à revenir sur un état précédent, on attend la fin de l'état actuel puis on retourne à l'historique de l'état désiré; celui-ci fini, on passe à l'état qui aurait du suivre celui pendant lequel on a demandé à revenir sur un état précédent*/
145                 QHistoryState* hState = historyValue(field);
146                 if(hState) { /*si l'historique existe (on a déjà quitté l'état voulu)*/
147                     hState->parentState()->addTransition(hState->parentState(), SIGNAL(next()), nextState);
148                     genPreviousState->addTransition(genPreviousState, SIGNAL(next()), hState);
149                 }
150             });
151         });
152     }
153 }
.fi
.SS "SH_InOutStateMachine::addIOState (\fBSH_InOutState\fP *state, QStringfield)\fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP 
.br
\fIfield\fP 
.RE
.PP

.PP
Définition à la ligne 112 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_ConfirmationState::confirmInput(), SH_InOutState::display(), SH_InOutStateMachine::displayCalendar(), SH_InOutStateMachine::displayFileDialog(), SH_InOutState::output(), SH_InOutState::rawInput(), SH_InOutStateMachine::receiveInput(), SH_InOutState::resendInput(), SH_InOutStateMachine::resendText(), SH_InOutState::sendOutput(), SH_InOutStateMachine::sendText(), SH_InOutStateMachine::setContentValue(), SH_InOutState::setInput(), SH_InOutStateMachine::setIOStateHistory(), SH_InOutState::setOutput(), SH_GenericState::toString(), SH_InOutStateMachine::validateInput(), et SH_InOutState::visibility()\&.
.PP
Référencé par SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), SH_ClientCreationStateMachine::SH_ClientCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
113 {
114     /*à faire au moment de l'entrée dans l'état state*/
115     connect(state, &QState::entered, [=]() {
116         qDebug() << state->toString() << "entered !";
117         state->display(true);
118         connect(this, &SH_InOutStateMachine::receiveInput, state, &SH_InOutState::setInput, Qt::QueuedConnection); /* la réception d'une valeur entraîne son enregistrement comme entrée de l'utilisateur auprès de l'état*/
119         connect(this, &SH_InOutStateMachine::receiveInput, [=](QString in){ qDebug() << state->toString() << "hello world !"; state->setInput(in);}); /* la réception d'une valeur entraîne son enregistrement comme entrée de l'utilisateur auprès de l'état*/
120         connect(state, &SH_InOutState::setOutput, [=](QVariant out) {qDebug() << state->toString() << "out !";});
121         connect(state, &SH_InOutState::sendOutput, [=](QVariant out) {qDebug() << state->toString() << "connected !"; emit this->sendText(out\&.toString(), false);});
122         connect(state, &SH_InOutState::resendInput, [=](QVariant in) {emit this->resendText(in\&.toString(), true);});
123         if(state->visibility()) {
124             state->sendOutput(QVariant(state->output()));
125         } else {
126             qDebug() << "invisible";
127         }
128     });
129     SH_ValidationState *validationState = qobject_cast<SH_ValidationState*>(state);
130     if(validationState) {
131         /*à faire au moment de l'entrée dans l'état state*/
132         connect(validationState, &QState::entered, [=]() {
133             connect(this, &SH_InOutStateMachine::validateInput, validationState, &SH_ValidationState::confirmInput, Qt::QueuedConnection);
134         });
135     }
136     SH_ConfirmationState *confirmationState = qobject_cast<SH_ConfirmationState*>(state);
137     if(confirmationState) {
138         /*à faire au moment de l'entrée dans l'état state*/
139         connect(confirmationState, &QState::entered, [=]() {
140             connect(this, &SH_InOutStateMachine::validateInput, confirmationState, &SH_ConfirmationState::confirmInput, Qt::QueuedConnection);
141         });
142     }
143     SH_DateQuestionState *dateState = qobject_cast<SH_DateQuestionState*>(state);
144     if(dateState) {
145         /*à faire au moment de l'entrée dans l'état state*/
146         connect(dateState, &QState::entered, this, &SH_InOutStateMachine::displayCalendar, Qt::QueuedConnection);
147     }
148     SH_FileSelectionState *fileState = qobject_cast<SH_FileSelectionState*>(state);
149     if(fileState) {
150         /*à faire au moment de l'entrée dans l'état state*/
151         connect(fileState, &QState::entered, this, &SH_InOutStateMachine::displayFileDialog, Qt::QueuedConnection);
152     }
153     /*à faire au moment de la sortie de l'état state*/
154     connect(state, &QState::exited, [=]() {
155         qDebug() << "exited !";
156         if(!field\&.isEmpty()) {
157             setContentValue(state->rawInput(), field);
158             /*gestion de l'historique des états pour pouvoir revenir à l'état state après l'avoir quitté*/
159             QHistoryState* hState = new QHistoryState(state);
160             setIOStateHistory(hState, field);
161         }
162         state->disconnect(this); /*plus aucune action sur l'état ne pourra être provoquée par la machine*/
163     });
164 
165 
166     QAbstractState* astate = qobject_cast<QAbstractState *>(state);
167     if(astate) {
168         addState(astate);
169     }
170 }
.fi
.SS "SH_InOutStateMachine::addIOStateMachine (\fBSH_InOutStateMachine\fP *fsm)\fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfsm\fP 
.RE
.PP

.PP
Définition à la ligne 178 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::cancelReplacement(), SH_InOutStateMachine::confirmInput(), SH_InOutStateMachine::displayCalendar(), SH_InOutStateMachine::receiveInput(), SH_InOutStateMachine::replaceInput(), SH_InOutStateMachine::resendText(), SH_InOutStateMachine::sendText(), et SH_InOutStateMachine::validateInput()\&.
.PP
Référencé par SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.PP
.nf
179 {
180     /*à faire au moment de l'entrée dans la machine d'état fsm*/
181     connect(fsm, &QState::entered, [=]() {
182         connect(this, &SH_InOutStateMachine::receiveInput, fsm, &SH_InOutStateMachine::receiveInput,Qt::QueuedConnection);
183         connect(this, &SH_InOutStateMachine::sendText, fsm, &SH_InOutStateMachine::sendText,Qt::QueuedConnection);
184         connect(this, &SH_InOutStateMachine::resendText, fsm, &SH_InOutStateMachine::resendText,Qt::QueuedConnection);
185         connect(this, &SH_InOutStateMachine::confirmInput, fsm, &SH_InOutStateMachine::confirmInput,Qt::QueuedConnection);
186         connect(this, &SH_InOutStateMachine::validateInput, fsm, &SH_InOutStateMachine::validateInput,Qt::QueuedConnection);
187         connect(this, &SH_InOutStateMachine::replaceInput, fsm, &SH_InOutStateMachine::replaceInput,Qt::QueuedConnection);
188         connect(this, &SH_InOutStateMachine::cancelReplacement, fsm, &SH_InOutStateMachine::cancelReplacement,Qt::QueuedConnection);
189         connect(this, &SH_InOutStateMachine::displayCalendar, fsm, &SH_InOutStateMachine::displayCalendar,Qt::QueuedConnection);
190     });
191     /*à faire au moment de la sortie de la machine d'état fsm*/
192     connect(fsm, &QState::exited, [=]() {
193         fsm->disconnect(this); /*plus aucune action sur la machine d'état fille ne pourra être provoquée par la machine mère*/
194     });
195 
196 }
.fi
.SS "SH_InOutStateMachine::cancelReplacement ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::cancelReplacement()\&.
.SS "SH_InOutStateMachine::clearAll ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addChildrenNextTransition(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::confirmInput ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOStateMachine(), SH_ApplicationCore::receiveConfirmation(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "Sh_LoopingInOutStateMachine::current () const"

.PP
\fBRenvoie:\fP
.RS 4
int 
.RE
.PP

.PP
Définition à la ligne 23 du fichier SH_LoopingIOStateMachine\&.cpp\&.
.PP
Références m_current\&.
.PP
Référencé par setCurrent(), et SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.PP
.nf
24 {
25     return m_current;
26 }
.fi
.SS "SH_InOutStateMachine::displayCalendar ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::displayFileDialog ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.SS "SH_InOutStateMachine::emitNext ()\fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
bool 
.RE
.PP

.PP
Définition à la ligne 326 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::next()\&.
.PP
Référencé par SH_AddressCreationStateMachine::SH_AddressCreationStateMachine()\&.
.PP
.nf
327 {
328     if(isRunning()) {
329         emit next();
330     }
331 }
.fi
.SS "SH_InOutStateMachine::getContentValue (QStringfield)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfield\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
QVariant 
.RE
.PP

.PP
Définition à la ligne 67 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioContent\&.
.PP
Référencé par SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ClientCreationStateMachine::SH_ClientCreationStateMachine()\&.
.PP
.nf
68 {
69     return m_ioContent\&.value(field);
70 }
.fi
.SS "SH_InOutStateMachine::historyValue (QStringfield)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfield\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
QHistoryState 
.RE
.PP

.PP
Définition à la ligne 241 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioStatesHistory\&.
.PP
Référencé par addChildrenNextTransition(), et SH_InOutStateMachine::addChildrenNextTransition()\&.
.PP
.nf
242 {
243     return m_ioStatesHistory\&.value(field);
244 }
.fi
.SS "SH_InOutStateMachine::ioContent () const\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QVariantMap 
.RE
.PP

.PP
Définition à la ligne 45 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioContent\&.
.PP
Référencé par SH_InOutStateMachine::setIOcontent()\&.
.PP
.nf
46 {
47     return m_ioContent;
48 }
.fi
.SS "SH_InOutStateMachine::ioStatesHistory () const\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QMap<QString, QHistoryState *> 
.RE
.PP

.PP
Définition à la ligne 205 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioStatesHistory\&.
.PP
Référencé par SH_InOutStateMachine::setIOStatesHistory()\&.
.PP
.nf
206 {
207     return m_ioStatesHistory;
208 }
.fi
.SS "bool SH_InOutStateMachine::isERunning ()\fC [protected]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 320 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_isRunning\&.
.PP
.nf
321 {
322     return m_isRunning;
323 }
.fi
.SS "int Sh_LoopingInOutStateMachine::limit () const"

.PP
Référencé par setLimit()\&.
.SS "Sh_LoopingInOutStateMachine::limitChanged ()\fC [signal]\fP"

.PP
Référencé par setLimit()\&.
.SS "SH_InOutStateMachine::next ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::emitNext(), et SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.SS "SH_InOutStateMachine::onEntry (QEvent *event)\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIevent\fP 
.RE
.PP

.PP
Définition à la ligne 301 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_isRunning, et SH_NamedObject::name()\&.
.PP
.nf
302 {
303     Q_UNUSED(event);
304     m_isRunning = true;
305     qDebug() << "Machine: " << machine()->objectName() << " entered " << name();
306 }
.fi
.SS "SH_InOutStateMachine::onExit (QEvent *event)\fC [protected]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIevent\fP 
.RE
.PP

.PP
Définition à la ligne 313 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_isRunning, et SH_NamedObject::name()\&.
.PP
.nf
314 {
315     Q_UNUSED(event);
316     m_isRunning = false;
317     qDebug() << "Machine: " << machine()->objectName() << " exited  " << name();
318 }
.fi
.SS "SH_InOutStateMachine::receiveInput (QStringinput)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIinput\fP 
.RE
.PP

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), SH_ApplicationCore::receiveInput(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "SH_InOutStateMachine::replaceInput (QStringfield)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIfield\fP 
.RE
.PP

.PP
Référencé par addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::replaceInput()\&.
.SS "void SH_InOutStateMachine::resendText (QStringtext, booleditable = \fCfalse\fP)\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::sendText (QStringtext, booleditable = \fCfalse\fP)\fC [signal]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fItext\fP 
.br
\fIeditable\fP 
.RE
.PP

.PP
Référencé par SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), et SH_ApplicationCore::connectRunningThread()\&.
.SS "SH_InOutStateMachine::setContentValue (QVariantcontent, QStringfield)\fC [slot]\fP, \fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIcontent\fP 
.br
\fIfield\fP 
.RE
.PP

.PP
Définition à la ligne 101 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioContent\&.
.PP
Référencé par addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::addIOState(), SH_ApplicationCore::launchBillThread(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ClientCreationStateMachine::SH_ClientCreationStateMachine()\&.
.PP
.nf
102 {
103     m_ioContent\&.insert(field, content);
104 }
.fi
.SS "Sh_LoopingInOutStateMachine::setCurrent (intcurrent)"

.PP
\fBParamètres:\fP
.RS 4
\fIcurrent\fP 
.RE
.PP

.PP
Définition à la ligne 34 du fichier SH_LoopingIOStateMachine\&.cpp\&.
.PP
Références current(), et m_current\&.
.PP
.nf
35 {
36     m_current = current;
37 }
.fi
.SS "SH_InOutStateMachine::setIOcontent (const QVariantMap &ioContent)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIioContent\fP 
.RE
.PP

.PP
Définition à la ligne 56 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::ioContent(), et SH_InOutStateMachine::m_ioContent\&.
.PP
.nf
57 {
58     m_ioContent = ioContent;
59 }
.fi
.SS "SH_InOutStateMachine::setIOStateHistory (QHistoryState *state, QStringfield)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP 
.br
\fIfield\fP 
.RE
.PP

.PP
Définition à la ligne 229 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_ioStatesHistory\&.
.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.PP
.nf
230 {
231     m_ioStatesHistory\&.insert(field, state); /*remplacement si plusieurs fois*/
232 }
.fi
.SS "Sh_LoopingInOutStateMachine::setLimit (intlimit)"

.PP
\fBParamètres:\fP
.RS 4
\fIlimit\fP 
.RE
.PP

.PP
Définition à la ligne 61 du fichier SH_LoopingIOStateMachine\&.cpp\&.
.PP
Références limit(), limitChanged(), et m_limit\&.
.PP
Référencé par SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.PP
.nf
62 {
63     m_limit = limit;
64     emit limitChanged();
65 }
.fi
.SS "Sh_LoopingInOutStateMachine::setPersistentContentValue (QVariantvalue, QStringfield)"

.PP
\fBParamètres:\fP
.RS 4
\fIcontent\fP 
.br
\fIfield\fP 
.RE
.PP

.PP
Définition à la ligne 39 du fichier SH_LoopingIOStateMachine\&.cpp\&.
.PP
Références m_persistentContent\&.
.PP
Référencé par SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.PP
.nf
40 {
41     m_persistentContent\&.insert(field, value);
42 }
.fi
.SS "SH_InOutStateMachine::setTableName (const QString &tableName)\fC [inherited]\fP"

.PP
\fBParamètres:\fP
.RS 4
\fItableName\fP 
.RE
.PP

.PP
Définition à la ligne 89 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_tableName, et SH_InOutStateMachine::tableName()\&.
.PP
.nf
90 {
91     m_tableName = tableName;
92 }
.fi
.SS "Sh_LoopingInOutStateMachine::stopLooping ()"

.PP
Définition à la ligne 72 du fichier SH_LoopingIOStateMachine\&.cpp\&.
.PP
Références m_current, et m_limit\&.
.PP
Référencé par SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
72                                               {
73     if(m_limit = 0) {
74         m_limit = m_current + 1;
75     } else {
76         m_current = m_limit - 1;
77     }
78 }
.fi
.SS "SH_InOutStateMachine::tableName () const\fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 78 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_InOutStateMachine::m_tableName\&.
.PP
Référencé par SH_InOutStateMachine::setTableName()\&.
.PP
.nf
79 {
80     return m_tableName;
81 }
.fi
.SS "SH_InOutStateMachine::toString ()\fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Réimplémentée à partir de \fBSH_NamedObject\fP\&.
.PP
Définition à la ligne 28 du fichier SH_IOStateMachine\&.cpp\&.
.PP
Références SH_NamedObject::toString(), et SH_GenericState::toString()\&.
.PP
Référencé par addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_ApplicationCore::launchBillingsThread(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), SH_InOutStateMachine::SH_InOutStateMachine(), et SH_GenericState::toString()\&.
.PP
.nf
29 {
30     QObject* parent = this->parent();
31     SH_GenericState* par = qobject_cast<SH_GenericState *>(parent);
32     if(par) {
33         return SH_NamedObject::toString()+ " [descending from "+par->toString()+"] ";
34     } else {
35         return SH_NamedObject::toString();
36     }
37 }
.fi
.SS "SH_InOutStateMachine::validateInput ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutStateMachine::addIOStateMachine(), SH_ApplicationCore::receiveValidation(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SH "Documentation des données membres"
.PP 
.SS "QList<QVariantMap> Sh_LoopingInOutStateMachine::m_contents\fC [private]\fP"

.PP
m_contents 
.PP
Définition à la ligne 99 du fichier SH_LoopingIOStateMachine\&.h\&.
.PP
Référencé par addChildrenNextTransition()\&.
.SS "int Sh_LoopingInOutStateMachine::m_current\fC [private]\fP"

.PP
m_current 
.PP
Définition à la ligne 95 du fichier SH_LoopingIOStateMachine\&.h\&.
.PP
Référencé par addChildrenNextTransition(), current(), setCurrent(), et stopLooping()\&.
.SS "QVariantMap SH_InOutStateMachine::m_ioContent\fC [protected]\fP, \fC [inherited]\fP"

.PP
m_ioContent 
.PP
Définition à la ligne 243 du fichier SH_IOStateMachine\&.h\&.
.PP
Référencé par addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::getContentValue(), SH_InOutStateMachine::ioContent(), SH_InOutStateMachine::setContentValue(), SH_InOutStateMachine::setIOcontent(), et SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.SS "QMap<QString, QHistoryState*> SH_InOutStateMachine::m_ioStatesHistory\fC [protected]\fP, \fC [inherited]\fP"

.PP
m_ioStatesHistory 
.PP
Définition à la ligne 253 du fichier SH_IOStateMachine\&.h\&.
.PP
Référencé par SH_InOutStateMachine::historyValue(), SH_InOutStateMachine::ioStatesHistory(), SH_InOutStateMachine::setIOStateHistory(), et SH_InOutStateMachine::setIOStatesHistory()\&.
.SS "int Sh_LoopingInOutStateMachine::m_limit\fC [private]\fP"

.PP
m_limit 
.PP
Définition à la ligne 91 du fichier SH_LoopingIOStateMachine\&.h\&.
.PP
Référencé par addChildrenNextTransition(), setLimit(), et stopLooping()\&.
.SS "QVariantMap Sh_LoopingInOutStateMachine::m_persistentContent\fC [private]\fP"

.PP
m_persistentContent 
.PP
Définition à la ligne 103 du fichier SH_LoopingIOStateMachine\&.h\&.
.PP
Référencé par addChildrenNextTransition(), et setPersistentContentValue()\&.
.SS "QString SH_InOutStateMachine::m_tableName\fC [protected]\fP, \fC [inherited]\fP"

.PP
m_tableName 
.PP
Définition à la ligne 248 du fichier SH_IOStateMachine\&.h\&.
.PP
Référencé par addChildrenNextTransition(), SH_InOutStateMachine::addChildrenNextTransition(), SH_InOutStateMachine::setTableName(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_InOutStateMachine::tableName()\&.
.SH "Documentation des propriétés"
.PP 
.SS "Sh_LoopingInOutStateMachine::limit\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
int 
.RE
.PP

.PP
Définition à la ligne 13 du fichier SH_LoopingIOStateMachine\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
