.TH "SH_OutputZone" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_OutputZone \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBRectangle\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBdisplay\fP (string text)"
.br
.ti -1c
.RI "void \fBdisplayNew\fP (string text, bool editable)"
.br
.ti -1c
.RI "void \fBdisplayNewFixed\fP (string text)"
.br
.ti -1c
.RI "void \fBdisplaySqlDatas\fP (variant sqlData)"
.br
.ti -1c
.RI "void \fBreplace\fP (string text)"
.br
.ti -1c
.RI "void \fBselected\fP (string selectedItem)"
.br
.ti -1c
.RI "void \fBselectedForDetail\fP (var sqlDatas)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBclear\fP (row)"
.br
.ti -1c
.RI "void \fBclearAll\fP ()"
.br
.ti -1c
.RI "void \fBdisplayCalendar\fP ()"
.br
.ti -1c
.RI "void \fBdisplayText\fP (text)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBlastVisibleRow\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_OutputZone\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_OutputZone::clear (row)"

.SS "void SH_OutputZone::clearAll ()"

.SS "void SH_OutputZone::display (stringtext)\fC [signal]\fP"

.SS "void SH_OutputZone::displayCalendar ()"

.SS "void SH_OutputZone::displayNew (stringtext, booleditable)\fC [signal]\fP"

.SS "void SH_OutputZone::displayNewFixed (stringtext)\fC [signal]\fP"

.SS "void SH_OutputZone::displaySqlDatas (variantsqlData)\fC [signal]\fP"

.SS "void SH_OutputZone::displayText (text)"

.SS "void SH_OutputZone::replace (stringtext)\fC [signal]\fP"

.SS "void SH_OutputZone::selected (stringselectedItem)\fC [signal]\fP"

.SS "void SH_OutputZone::selectedForDetail (varsqlDatas)\fC [signal]\fP"

.SH "Documentation des propriétés"
.PP 
.SS "int SH_OutputZone::lastVisibleRow"

.PP
Définition à la ligne 7 du fichier SH_OutputZone\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
