.TH "SH_RoomsSectionsDelegate" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_RoomsSectionsDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBRectangle\fP\&.
.SS "Propriétés"

.in +1c
.ti -1c
.RI "string \fBvalue\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_RoomsSectionsDelegate\&.qml\&.
.SH "Documentation des propriétés"
.PP 
.SS "string SH_RoomsSectionsDelegate::value"

.PP
Définition à la ligne 7 du fichier SH_RoomsSectionsDelegate\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
