.TH "SH_RegExpQuestionState" 3 "Vendredi Juin 21 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_RegExpQuestionState \- 
.PP
The \fBSH_RegExpQuestionState\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_RegExpQuestionState\&.h>\fP
.PP
Est dérivée de \fBSH_StringQuestionState\fP\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "virtual void \fBsetOutput\fP (const QString &\fBoutput\fP)"
.br
.ti -1c
.RI "virtual void \fBsetVisibility\fP (bool isVisible)"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBanswerInvalid\fP ()"
.br
.RI "\fIanswerInvalid \fP"
.ti -1c
.RI "void \fBanswerValid\fP ()"
.br
.RI "\fIanswerValid \fP"
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBresendInput\fP (QVariant \fBinput\fP)"
.br
.ti -1c
.RI "void \fBsendOutput\fP (QVariant \fBoutput\fP)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSH_RegExpQuestionState\fP (QString question, QString \fBname\fP, QRegularExpression regex=QRegularExpression(), \fBQState\fP *parent=0)"
.br
.ti -1c
.RI "bool \fBcheckValidity\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP (bool canDisplay)"
.br
.ti -1c
.RI "virtual QVariant \fBgivenAnswer\fP () const "
.br
.ti -1c
.RI "virtual QVariant \fBinput\fP () const "
.br
.ti -1c
.RI "virtual bool \fBisAnswerValid\fP (const QVariant &\fBgivenAnswer\fP)"
.br
.ti -1c
.RI "int \fBmaxLen\fP () const "
.br
.ti -1c
.RI "int \fBminLen\fP () const "
.br
.ti -1c
.RI "void \fBonExit\fP (QEvent *event)"
.br
.ti -1c
.RI "virtual QString \fBoutput\fP () const "
.br
.ti -1c
.RI "virtual QVariant \fBrawInput\fP () const "
.br
.ti -1c
.RI "QRegularExpression \fBregexp\fP () const "
.br
.ti -1c
.RI "virtual void \fBsetGivenAnswer\fP (const QVariant &\fBgivenAnswer\fP)"
.br
.ti -1c
.RI "virtual void \fBsetInput\fP (const QVariant &\fBinput\fP)"
.br
.ti -1c
.RI "void \fBsetMaxLen\fP (int \fBmaxLen\fP)"
.br
.ti -1c
.RI "void \fBsetMinLen\fP (int \fBminLen\fP)"
.br
.ti -1c
.RI "void \fBsetRegexp\fP (const QRegularExpression &\fBregexp\fP)"
.br
.ti -1c
.RI "QString \fBtoString\fP ()"
.br
.ti -1c
.RI "bool \fBvisibility\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void \fBonEntry\fP (QEvent *event)"
.br
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "QRegularExpression \fBm_regexp\fP"
.br
.RI "\fIm_regexp \fP"
.in -1c
.SH "Description détaillée"
.PP 
The \fBSH_RegExpQuestionState\fP class\&. 
.PP
Définition à la ligne 8 du fichier SH_RegExpQuestionState\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "SH_RegExpQuestionState::SH_RegExpQuestionState (QStringquestion, QStringname, QRegularExpressionregex = \fCQRegularExpression()\fP, \fBQState\fP *parent = \fC0\fP)"

.PP
Définition à la ligne 8 du fichier SH_RegExpQuestionState\&.cpp\&.
.PP
.nf
8                                                                                                                        :
9     SH_StringQuestionState(question, name, 0,-1,parent)
10 {
11 }
.fi
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_QuestionState::answerInvalid ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
answerInvalid 
.PP
Référencé par SH_QuestionState::checkValidity(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "void SH_QuestionState::answerValid ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
answerValid 
.PP
Référencé par SH_QuestionState::checkValidity(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "bool SH_QuestionState::checkValidity ()\fC [inherited]\fP"

.PP
Définition à la ligne 20 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::answerInvalid(), SH_QuestionState::answerValid(), SH_QuestionState::givenAnswer(), SH_QuestionState::isAnswerValid(), SH_GenericState::next(), et SH_InOutState::setInput()\&.
.PP
Référencé par SH_QuestionState::setGivenAnswer()\&.
.PP
.nf
21 {
22     bool ok = this->isAnswerValid(this->givenAnswer());
23     if(ok) {
24         qDebug() << this->givenAnswer() << " answer valid !";
25         qDebug() << this->givenAnswer();
26         SH_InOutState::setInput(this->givenAnswer());
27         emit answerValid();
28         emit next();
29     } else {
30         qDebug() << this->givenAnswer() << " answer invalid :-(";
31         qDebug() << this->givenAnswer();
32         emit answerInvalid();
33     }
34     return ok;
35 }
.fi
.SS "void SH_InOutState::display (boolcanDisplay)\fC [inherited]\fP"

.PP
Définition à la ligne 95 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_display, SH_InOutState::m_isVisible, SH_InOutState::m_output, et SH_InOutState::sendOutput()\&.
.PP
Référencé par SH_InOutStateMachine::addIOState(), et SH_StatementState::onEntry()\&.
.PP
.nf
96 {
97     m_display=canDisplay;
98     if(m_display && !m_output\&.isEmpty() && m_isVisible) {
99         qDebug() << "resalut !" << QVariant(m_output);
100         emit sendOutput(QVariant(m_output));
101     }
102 }
.fi
.SS "QVariant SH_QuestionState::givenAnswer () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 55 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::m_givenAnswer\&.
.PP
Référencé par SH_QuestionState::checkValidity(), SH_DatabaseContentQuestionState::rawInput(), et SH_BillingCreationStateMachine::SH_BillingCreationStateMachine()\&.
.PP
.nf
56 {
57     return this->m_givenAnswer;
58 }
.fi
.SS "QVariant SH_InOutState::input () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 20 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_input\&.
.PP
Référencé par SH_InOutState::rawInput(), SH_DateQuestionState::rawInput(), et SH_InOutState::setInput()\&.
.PP
.nf
21 {
22     return m_input;
23 }
.fi
.SS "bool SH_RegExpQuestionState::isAnswerValid (const QVariant &givenAnswer)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBSH_StringQuestionState\fP\&.
.PP
Définition à la ligne 18 du fichier SH_RegExpQuestionState\&.cpp\&.
.PP
Références m_regexp\&.
.PP
.nf
19 {
20     QString answer = givenAnswer\&.toString();
21     QRegularExpressionMatch found = m_regexp\&.match(answer);
22     return (found\&.hasMatch() && (found\&.captured(0) == answer));
23 }
.fi
.SS "int SH_StringQuestionState::maxLen () const\fC [inherited]\fP"

.PP
Définition à la ligne 39 du fichier SH_StringQuestionState\&.cpp\&.
.PP
Références SH_StringQuestionState::m_maxLen\&.
.PP
Référencé par SH_StringQuestionState::setMaxLen()\&.
.PP
.nf
40 {
41     return m_maxLen;
42 }
.fi
.SS "int SH_StringQuestionState::minLen () const\fC [inherited]\fP"

.PP
Définition à la ligne 61 du fichier SH_StringQuestionState\&.cpp\&.
.PP
Références SH_StringQuestionState::m_minLen\&.
.PP
Référencé par SH_StringQuestionState::setMinLen()\&.
.PP
.nf
62 {
63     return m_minLen;
64 }
.fi
.SS "void SH_GenericState::next ()\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_QuestionState::checkValidity(), SH_ConfirmationState::confirmInput(), SH_AdaptDatabaseState::insertUpdate(), SH_StatementState::onEntry(), SH_BillingCreationStateMachine::SH_BillingCreationStateMachine(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.SS "void SH_GenericState::onEntry (QEvent *event)\fC [protected]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 62 du fichier SH_GenericDebugableState\&.cpp\&.
.PP
Références SH_NamedObject::name()\&.
.PP
Référencé par SH_StatementState::onEntry()\&.
.PP
.nf
63 {
64     Q_UNUSED(event);
65     qDebug() << "Machine: " << machine()->objectName() << " entered " << name();
66 }
.fi
.SS "void SH_InOutState::onExit (QEvent *event)\fC [inherited]\fP"

.PP
Définition à la ligne 110 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_input, SH_InOutState::m_isVisible, SH_GenericState::onExit(), et SH_InOutState::resendInput()\&.
.PP
.nf
111 {
112     SH_GenericState::onExit(event);
113     if(m_isVisible) {
114         emit resendInput(m_input);
115     }
116 }
.fi
.SS "QString SH_InOutState::output () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 56 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_output\&.
.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutState::setOutput(), et SH_StatementState::SH_StatementState()\&.
.PP
.nf
57 {
58     return m_output;
59 }
.fi
.SS "QVariant SH_InOutState::rawInput () const\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Réimplémentée dans \fBSH_DateQuestionState\fP, et \fBSH_DatabaseContentQuestionState\fP\&.
.PP
Définition à la ligne 30 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::input()\&.
.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.PP
.nf
31 {
32     return input();
33 }
.fi
.SS "QRegularExpression SH_RegExpQuestionState::regexp () const"

.PP
Définition à la ligne 31 du fichier SH_RegExpQuestionState\&.cpp\&.
.PP
Références m_regexp\&.
.PP
Référencé par setRegexp()\&.
.PP
.nf
32 {
33     return m_regexp;
34 }
.fi
.SS "void SH_InOutState::resendInput (QVariantinput)\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutState::onExit(), et SH_InOutState::setInput()\&.
.SS "void SH_InOutState::sendOutput (QVariantoutput)\fC [signal]\fP, \fC [inherited]\fP"

.PP
Référencé par SH_InOutStateMachine::addIOState(), SH_InOutState::display(), et SH_InOutState::setOutput()\&.
.SS "void SH_QuestionState::setGivenAnswer (const QVariant &givenAnswer)\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 66 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::checkValidity(), et SH_QuestionState::m_givenAnswer\&.
.PP
Référencé par SH_QuestionState::setInput()\&.
.PP
.nf
67 {
68     this->m_givenAnswer = givenAsnwer;
69     this->checkValidity();
70 }
.fi
.SS "void SH_QuestionState::setInput (const QVariant &input)\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Réimplémentée à partir de \fBSH_InOutState\fP\&.
.PP
Définition à la ligne 43 du fichier SH_QuestionState\&.cpp\&.
.PP
Références SH_QuestionState::setGivenAnswer()\&.
.PP
Référencé par SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
44 {
45     qDebug() << "new answer " << input\&.toString();
46     this->setGivenAnswer(input);
47 }
.fi
.SS "void SH_StringQuestionState::setMaxLen (intmaxLen)\fC [inherited]\fP"

.PP
Définition à la ligne 50 du fichier SH_StringQuestionState\&.cpp\&.
.PP
Références SH_StringQuestionState::m_maxLen, et SH_StringQuestionState::maxLen()\&.
.PP
.nf
51 {
52     m_maxLen = maxLen;
53 }
.fi
.SS "void SH_StringQuestionState::setMinLen (intminLen)\fC [inherited]\fP"

.PP
Définition à la ligne 72 du fichier SH_StringQuestionState\&.cpp\&.
.PP
Références SH_StringQuestionState::m_minLen, et SH_StringQuestionState::minLen()\&.
.PP
.nf
73 {
74     m_minLen = minLen;
75 }
.fi
.SS "void SH_InOutState::setOutput (const QString &output)\fC [virtual]\fP, \fC [slot]\fP, \fC [inherited]\fP"

.PP
Réimplémentée dans \fBSH_DatabaseContentQuestionState\fP\&.
.PP
Définition à la ligne 68 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_isVisible, SH_InOutState::m_output, SH_InOutState::output(), et SH_InOutState::sendOutput()\&.
.PP
Référencé par SH_DatabaseContentQuestionState::setOutput(), et SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
69 {
70     m_output = output;
71     if(m_isVisible) {
72         emit sendOutput(QVariant(m_output));
73     }
74 }
.fi
.SS "void SH_RegExpQuestionState::setRegexp (const QRegularExpression &regexp)"

.PP
Définition à la ligne 41 du fichier SH_RegExpQuestionState\&.cpp\&.
.PP
Références m_regexp, et regexp()\&.
.PP
.nf
42 {
43     m_regexp = regexp;
44 }
.fi
.SS "void SH_InOutState::setVisibility (boolisVisible)\fC [virtual]\fP, \fC [slot]\fP, \fC [inherited]\fP"

.PP
Définition à la ligne 81 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_isVisible\&.
.PP
Référencé par SH_ServiceCharging::SH_ServiceCharging()\&.
.PP
.nf
82 {
83     m_isVisible = isVisible;
84 }
.fi
.SS "QString SH_GenericState::toString ()\fC [virtual]\fP, \fC [inherited]\fP"

.PP
Réimplémentée à partir de \fBSH_NamedObject\fP\&.
.PP
Définition à la ligne 21 du fichier SH_GenericDebugableState\&.cpp\&.
.PP
Références SH_NamedObject::toString(), et SH_InOutStateMachine::toString()\&.
.PP
Référencé par SH_InOutStateMachine::addChildrenNextTransition(), SH_DateQuestionState::rawInput(), et SH_InOutStateMachine::toString()\&.
.PP
.nf
22 {
23     QStateMachine* machine = this->machine();
24     SH_InOutStateMachine* mach = qobject_cast<SH_InOutStateMachine *>(machine);
25     if(mach) {
26         return SH_NamedObject::toString()+ " [in "+mach->toString()+"] ";
27     } else {
28         return SH_NamedObject::toString();
29     }
30 }
.fi
.SS "bool SH_InOutState::visibility ()\fC [inherited]\fP"

.PP
Définition à la ligne 91 du fichier SH_IOState\&.cpp\&.
.PP
Références SH_InOutState::m_isVisible\&.
.PP
Référencé par SH_InOutStateMachine::addIOState()\&.
.PP
.nf
91                                {
92     return m_isVisible;
93 }
.fi
.SH "Documentation des données membres"
.PP 
.SS "QRegularExpression SH_RegExpQuestionState::m_regexp\fC [private]\fP"

.PP
m_regexp 
.PP
Définition à la ligne 51 du fichier SH_RegExpQuestionState\&.h\&.
.PP
Référencé par isAnswerValid(), regexp(), et setRegexp()\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
