.TH "SH_SqlDataFields" 3 "Lundi Juin 24 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_SqlDataFields \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_SqlDataField\&.h>\fP
.PP
Est dérivée de \fBQQuickItem\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBnameChanged\fP ()"
.br
.ti -1c
.RI "void \fBroleChanged\fP ()"
.br
.ti -1c
.RI "void \fBsortOrderChanged\fP ()"
.br
.ti -1c
.RI "void \fBtextChanged\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSH_SqlDataFields\fP (\fBQQuickItem\fP *parent=0)"
.br
.ti -1c
.RI "QString \fBname\fP () const "
.br
.ti -1c
.RI "QByteArray \fBrole\fP () const "
.br
.ti -1c
.RI "void \fBsetName\fP (QString newName)"
.br
.ti -1c
.RI "void \fBsetSortOrder\fP (Qt::SortOrder newSortOrder)"
.br
.ti -1c
.RI "void \fBsetText\fP (QString newText)"
.br
.ti -1c
.RI "Qt::SortOrder \fBsortOrder\fP () const "
.br
.ti -1c
.RI "QString \fBtext\fP () const "
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QByteArray \fBrole\fP"
.br
.ti -1c
.RI "Qt::SortOrder \fBsortOrder\fP"
.br
.ti -1c
.RI "QString \fBtext\fP"
.br
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "QString \fBm_name\fP"
.br
.RI "\fIm_name \fP"
.ti -1c
.RI "Qt::SortOrder \fBm_sortOrder\fP"
.br
.RI "\fIm_sortOrder \fP"
.ti -1c
.RI "QString \fBm_text\fP"
.br
.RI "\fIm_text \fP"
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 12 du fichier SH_SqlDataField\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "SH_SqlDataFields::SH_SqlDataFields (\fBQQuickItem\fP *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Définition à la ligne 8 du fichier SH_SqlDataField\&.cpp\&.
.PP
.nf
8                                                      :
9     QQuickItem(parent)
10 {
11     this->setHeight(15);
12 }
.fi
.SH "Documentation des fonctions membres"
.PP 
.SS "QString SH_SqlDataFields::name () const\fC [inline]\fP"

.PP
Définition à la ligne 42 du fichier SH_SqlDataField\&.h\&.
.PP
Références m_name\&.
.PP
.nf
42 { return m_name; }
.fi
.SS "SH_SqlDataFields::nameChanged ()\fC [signal]\fP"

.PP
Référencé par setName()\&.
.SS "QByteArray SH_SqlDataFields::role () const\fC [inline]\fP"

.PP
Définition à la ligne 49 du fichier SH_SqlDataField\&.h\&.
.PP
Références m_name\&.
.PP
.nf
49 { return QByteArray(m_name\&.toUpper()\&.toStdString()\&.c_str()); }
.fi
.SS "SH_SqlDataFields::roleChanged ()\fC [signal]\fP"

.PP
Référencé par setName()\&.
.SS "SH_SqlDataFields::setName (QStringnewName)"

.PP
\fBParamètres:\fP
.RS 4
\fInewName\fP 
.RE
.PP

.PP
Définition à la ligne 35 du fichier SH_SqlDataField\&.cpp\&.
.PP
Références m_name, m_text, nameChanged(), roleChanged(), setSortOrder(), et setText()\&.
.PP
Référencé par SH_SqlDataModel::fetch(), SH_SqlDataModel::setFields(), et setText()\&.
.PP
.nf
36 {
37     m_name = newName;
38     this->setSortOrder(Qt::AscendingOrder);
39     if (m_text == "")
40     {
41         this->setText(m_name);
42     }
43     emit nameChanged();
44     emit roleChanged();
45 }
.fi
.SS "SH_SqlDataFields::setSortOrder (Qt::SortOrdernewSortOrder)"

.PP
\fBParamètres:\fP
.RS 4
\fInewSortOrder\fP 
.RE
.PP

.PP
Définition à la ligne 54 du fichier SH_SqlDataField\&.cpp\&.
.PP
Références m_sortOrder, et sortOrderChanged()\&.
.PP
Référencé par SH_BillingsTableModel::fillModel(), SH_BookingsTableModel::fillModel(), setName(), et SH_ExtendedProxyModel::sort()\&.
.PP
.nf
55 {
56     m_sortOrder = newSortOrder;
57     emit sortOrderChanged();
58 }
.fi
.SS "SH_SqlDataFields::setText (QStringnewText)"

.PP
\fBParamètres:\fP
.RS 4
\fInewText\fP 
.RE
.PP

.PP
Définition à la ligne 19 du fichier SH_SqlDataField\&.cpp\&.
.PP
Références m_name, m_text, setName(), et textChanged()\&.
.PP
Référencé par setName()\&.
.PP
.nf
20 {
21     m_text = newText;
22     if (m_name == "")
23     {
24         this->setName(m_text\&.toUpper());
25     }
26     emit textChanged();
27 }
.fi
.SS "Qt::SortOrder SH_SqlDataFields::sortOrder () const\fC [inline]\fP"

.PP
Définition à la ligne 56 du fichier SH_SqlDataField\&.h\&.
.PP
Références m_sortOrder\&.
.PP
.nf
56 { return m_sortOrder; }
.fi
.SS "SH_SqlDataFields::sortOrderChanged ()\fC [signal]\fP"

.PP
Référencé par setSortOrder()\&.
.SS "QString SH_SqlDataFields::text () const\fC [inline]\fP"

.PP
Définition à la ligne 35 du fichier SH_SqlDataField\&.h\&.
.PP
Références m_text\&.
.PP
.nf
35 { return m_text; }
.fi
.SS "SH_SqlDataFields::textChanged ()\fC [signal]\fP"

.PP
Référencé par setText()\&.
.SH "Documentation des données membres"
.PP 
.SS "QString SH_SqlDataFields::m_name\fC [private]\fP"

.PP
m_name 
.PP
Définition à la ligne 88 du fichier SH_SqlDataField\&.h\&.
.PP
Référencé par name(), role(), setName(), et setText()\&.
.SS "Qt::SortOrder SH_SqlDataFields::m_sortOrder\fC [private]\fP"

.PP
m_sortOrder 
.PP
Définition à la ligne 92 du fichier SH_SqlDataField\&.h\&.
.PP
Référencé par setSortOrder(), et sortOrder()\&.
.SS "QString SH_SqlDataFields::m_text\fC [private]\fP"

.PP
m_text 
.PP
Définition à la ligne 84 du fichier SH_SqlDataField\&.h\&.
.PP
Référencé par setName(), setText(), et text()\&.
.SH "Documentation des propriétés"
.PP 
.SS "SH_SqlDataFields::name\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 15 du fichier SH_SqlDataField\&.h\&.
.PP
Référencé par SH_SqlDataModel::fetch()\&.
.SS "SH_SqlDataFields::role\fC [read]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QByteArray 
.RE
.PP

.PP
Définition à la ligne 17 du fichier SH_SqlDataField\&.h\&.
.SS "SH_SqlDataFields::sortOrder\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
Qt::SortOrder 
.RE
.PP

.PP
Définition à la ligne 18 du fichier SH_SqlDataField\&.h\&.
.PP
Référencé par SH_ExtendedProxyModel::setSortKeyColumn()\&.
.SS "SH_SqlDataFields::text\fC [read]\fP, \fC [write]\fP"

.PP
\fBRenvoie:\fP
.RS 4
QString 
.RE
.PP

.PP
Définition à la ligne 16 du fichier SH_SqlDataField\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
