.TH "SH_ServicesDelegate" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_ServicesDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBSH_DataDelegate\fP\&.
.SS "Propriétés"

.in +1c
.ti -1c
.RI "bool \fBenableRoomNeeded\fP"
.br
.ti -1c
.RI "int \fBfontSize\fP"
.br
.ti -1c
.RI "string \fBvalue\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_ServicesDelegate\&.qml\&.
.SH "Documentation des propriétés"
.PP 
.SS "bool SH_ServicesDelegate::enableRoomNeeded"

.PP
Définition à la ligne 7 du fichier SH_ServicesDelegate\&.qml\&.
.SS "int SH_DataDelegate::fontSize\fC [inherited]\fP"

.PP
Définition à la ligne 9 du fichier SH_DataDelegate\&.qml\&.
.SS "string SH_DataDelegate::value\fC [inherited]\fP"

.PP
Définition à la ligne 7 du fichier SH_DataDelegate\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
