.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_Trainee.h" 3 "Lundi Juin 24 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_Trainee.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SH_User\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSH_Trainee\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
