.TH "/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_VATTableModel.h" 3 "Mardi Juillet 2 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tiff/Stage-IUT/app/simplhotel/hotel-precheck/src/PreCheck/models/SH_VATTableModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SH_ExtendedSqlProxyModel\&.h'\fP
.br
\fC#include 'SH_SqlDataField\&.h'\fP
.br
\fC#include <QtQml>\fP
.br
\fC#include <QtQuick>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSH_VATTableModel\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
