.TH "SH_WelcomePage" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_WelcomePage \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBItem\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBclicked\fP ()"
.br
.ti -1c
.RI "void \fBloggedOut\fP ()"
.br
.ti -1c
.RI "void \fBlogOut\fP ()"
.br
.ti -1c
.RI "void \fBquit\fP ()"
.br
.ti -1c
.RI "void \fBreload\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_WelcomePage\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_WelcomePage::clicked ()\fC [signal]\fP"

.SS "void SH_WelcomePage::loggedOut ()\fC [signal]\fP"

.SS "void SH_WelcomePage::logOut ()\fC [signal]\fP"

.SS "void SH_WelcomePage::quit ()\fC [signal]\fP"

.SS "void SH_WelcomePage::reload ()\fC [signal]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
