.TH "SimpleHotel::SH_Company" 3 "Lundi Juin 24 2013" "Version 0.4" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleHotel::SH_Company \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SH_Company\&.h>\fP
.PP
Est dérivée de \fBQObject\fP\&.
.SH "Description détaillée"
.PP 
Définition à la ligne 13 du fichier SH_Company\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
