CONNECT "PreCheckDB.fbd" USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;

DROP DATABASE;

COMMIT;

CREATE DATABASE "PreCheckDB.fdb" USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;

CONNECT "PreCheckDB.fdb" USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;

CREATE DOMAIN BOOLEAN AS CHAR(1) CHECK (value is null or value in ('','0', '1'));

COMMIT;
