CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;

CREATE TABLE SERVICESFIELDS
 (
 ID SERIAL,
 LABEL VARCHAR(25) NOT NULL,
 SQLTYPE VARCHAR(100) DEFAULT 'TEXT' NOT NULL,
 CONSTRAINT PK_SERVICESFIELDS_ID PRIMARY KEY (ID),
 CONSTRAINT UQ_SERVICESFIELDS_LABEL UNIQUE (LABEL)
 );


 COMMIT;
