CONNECT TO "PreCheckDB" AS precheck-hotel USER 'precheck' USING 'hotel';

COMMIT;


CREATE TABLE USERS
(
ID SERIAL,
LOGIN VARCHAR(20) NOT NULL,
ENCRYPTEDPASS VARCHAR(255) NOT NULL,
ISRECEPTIONIST BOOLEAN DEFAULT '0' NOT NULL,
ISMANAGERX BOOLEAN DEFAULT '0' NOT NULL,
ISMANAGERZ BOOLEAN DEFAULT '0' NOT NULL,
ISADMINISTRATOR BOOLEAN DEFAULT '0' NOT NULL,
CONSTRAINT PK_USERS_ID PRIMARY KEY (ID),
CONSTRAINT UQ_USERS_LOGIN UNIQUE (LOGIN)
);


 COMMIT;
