CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;


CREATE TABLE BILLINGSTYPES
(
ID INTEGER NOT NULL,
LABEL VARCHAR(20),
NBBILLS INT NOT NULL,
CONSTRAINT PK_BILLINGSTYPES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_BILLINGSTYPES_LABEL UNIQUE (LABEL)
);

CREATE SEQUENCE SEQ_BILLINGSTYPES_ID;

 SET TERM !! ;
 CREATE TRIGGER TR_BILLINGSTYPES_AUTOID for BILLINGSTYPES
 active before insert position 0
 as
 begin
 if ((new.ID is null) or (new.ID = 0)) then
 begin
 new.id = NEXT VALUE FOR SEQ_BILLINGSTYPES_ID;
 end
 end!!
 SET TERM ; !!

 COMMIT;
