CONNECT TO "PreCheckDB" AS precheck-hotel USER 'precheck' USING 'hotel';

COMMIT;


CREATE TABLE CHARGEDSERVICES
(
SERVICE_ID INTEGER NOT NULL,
BILL_ID INTEGER NOT NULL,
RECEPTIONIST_ID INTEGER NOT NULL,
INVOICINGDATE DATE NOT NULL,
QUANTITY INT NOT NULL,
CHARGEDUNITYPRICE FLOAT,
VAT_PERCENTAGE FLOAT,
ISPRINTED BOOLEAN DEFAULT '0' NOT NULL,
ISPAYED BOOLEAN DEFAULT '0' NOT NULL,
PAIEMENTDATE DATE,
CONSTRAINT PK_CHARGEDSERVICES_SERVICEBILL PRIMARY KEY (SERVICE_ID,BILL_ID)
);


COMMIT;
