CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;

CREATE TABLE SERVICES
(
ID INTEGER NOT NULL,
SERVICETYPE_ID INTEGER NOT NULL,
NAME VARCHAR(100) NOT NULL,
ISAVAILABLE BOOLEAN DEFAULT '1'  NOT NULL,
CONSTRAINT PK_SERVICES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_SERVICES_NAME UNIQUE (NAME)
);

CREATE SEQUENCE SEQ_SERVICES_ID;

 SET TERM !! ;
 CREATE TRIGGER TR_SERVICES_AUTOID for SERVICES
 active before insert position 0
 as
 begin
 if ((new.ID is null) or (new.ID = 0)) then
 begin
 new.id = NEXT VALUE FOR SEQ_SERVICES_ID;
 end
 end!!
 SET TERM ; !!

 COMMIT;
