CONNECT TO "PreCheckDB" AS precheck-hotel USER 'precheck' USING 'hotel';

COMMIT;

CREATE TABLE BILLS
(
ID SERIAL,
BILLING_ID INTEGER NOT NULL,
BILLINGBILLID INTEGER NOT NULL,
BILLTYPE_ID INTEGER NOT NULL,
NOTE VARCHAR(255),
CONSTRAINT PK_BILLS_ID PRIMARY KEY (ID),
CONSTRAINT UQ_BILLS_IDBILLID UNIQUE (BILLING_ID,BILLINGBILLID)
);


COMMIT;
