CONNECT 'localhost:/home/tiff/Stage-IUT/app/hotel-precheck/src/PreCheck/Database/PreCheckDB.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;

CREATE TABLE BILLS
(
ID INTEGER NOT NULL,
BILLING_ID INTEGER NOT NULL,
BILLINGBILLID INTEGER NOT NULL,
BILLTYPE_ID INTEGER NOT NULL,
NOTE VARCHAR(255),
CONSTRAINT PK_BILLS_ID PRIMARY KEY (ID),
CONSTRAINT UQ_BILLS_IDBILLID UNIQUE (BILLING_ID,BILLING_BILLID)
);

CREATE SEQUENCE SEQ_BILLS_ID;

SET TERM !! ;
CREATE TRIGGER TR_BILLS_AUTOID FOR BILLS
ACTIVE BEFORE INSERT position 0
AS
BEGIN
IF ((new.ID IS NULL) OR (new.ID = 0)) THEN
BEGIN
new.id = gen_id(SEQ_BILLS_ID,1);
END
END!!
SET TERM ; !!

COMMIT;
