CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;


CREATE TABLE BILLINGSTYPES
(
ID SERIAL,
LABEL VARCHAR(20),
NBBILLS INT NOT NULL,
CONSTRAINT PK_BILLINGSTYPES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_BILLINGSTYPES_LABEL UNIQUE (LABEL)
);


 COMMIT;
