CONNECT 'localhost:/home/tiff/Stage-IUT/app/hotel-precheck/src/PreCheck/Database/PreCheckDB.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;


CREATE TABLE CLIENTS
(
ID INTEGER NOT NULL,
NAME VARCHAR(35) NOT NULL,
PHONE VARCHAR(12),
EMAIL VARCHAR(50),
IDCARDSCAN VARCHAR(100),
NATIONALITY_ID INTEGER NOT NULL,
HOMEADDRESS_ID INTEGER,
ISCURRENT BOOLEAN DEFAULT '0' NOT NULL,
CONSTRAINT PK_CLIENTS_ID PRIMARY KEY (ID),
CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL),
CONSTRAINT CK_VAL_CLIENTS_EMAIL CHECK(EMAIL SIMILAR TO '[[[:ALNUM:]\._%\+\-]+@[[:ALNUM:]\.-]+\.[[:ALPHA:]]+]?'),
CONSTRAINT CK_VAL_CLIENTS_PHONE CHECK(PHONE SIMILAR TO '[[\+|00][[1-9]]{3}[[:DIGIT:]]{8}]?')
);

CREATE SEQUENCE SEQ_CLIENTS_ID;

 SET TERM !! ;
 CREATE TRIGGER TR_CLIENTS_AUTOID for CLIENTS
 active before insert position 0
 as
 begin
 if ((new.ID is null) or (new.ID = 0)) then
 begin
 new.id = gen_id(SEQ_CLIENTS_ID,1);
 end
 end!!
 SET TERM ; !!

 COMMIT;
