CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;

CREATE TABLE SERVICES
(
ID SERIAL,
SERVICETYPE_ID INTEGER NOT NULL,
NAME VARCHAR(100) NOT NULL,
ISAVAILABLE BOOLEAN DEFAULT '1'  NOT NULL,
CONSTRAINT PK_SERVICES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_SERVICES_NAME UNIQUE (NAME)
);


 COMMIT;
