CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;


CREATE TABLE NATIONALITIES
(
ID INTEGER NOT NULL,
CODE VARCHAR(3) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
LABEL VARCHAR(50) NOT NULL,
CONSTRAINT PK_NATIONALITIES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_NATIONALITIES_CODE UNIQUE (CODE),
CONSTRAINT UQ_NATIONALITIES_LABEL UNIQUE (LABEL)
);

CREATE SEQUENCE SEQ_NATIONALITIES_ID;

 SET TERM !! ;
 CREATE TRIGGER TR_NATIONALITIES_AUTOID for NATIONALITIES
 active before insert position 0
 as
 begin
 if ((new.ID is null) or (new.ID = 0)) then
 begin
 new.id = gen_id(SEQ_NATIONALITIES_ID,1);
 end
 end!!
 SET TERM ; !!

 COMMIT;
