CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;

CREATE TABLE TAXES
(
ID SERIAL,
LABEL VARCHAR(20) NOT NULL,
PERCENTAGE FLOAT,
STARTDATE DATE,
ENDDATE DATE,
CONSTRAINT PK_TAXES_ID PRIMARY KEY (ID)
);

 COMMIT;
