CONNECT TO "PreCheckDB" AS precheck-hotel USER 'precheck' USING 'hotel';

COMMIT;

CREATE TABLE ROOMSTYPES
(
ID SERIAL,
LABEL VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(255),
PRICEMIN FLOAT NOT NULL,
PRICEMAX FLOAT,
CONSTRAINT PK_ROOMSTYPES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_ROOMSTYPES_LABEL UNIQUE (LABEL)
);


 COMMIT;
