CONNECT 'localhost:/home/tiff/Stage-IUT/app/hotel-precheck/src/PreCheck/Database/PreCheckDB.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;

CREATE TABLE SERVICES
(
ID INTEGER NOT NULL,
SERVICETYPE_ID INTEGER NOT NULL,
DISPLAYEDNAME VARCHAR(100) NOT NULL,
PRINTEDNAME VARCHAR(100),
PRICE1 FLOAT NOT NULL,
PRICE2 FLOAT,
ISAVAILABLE BOOLEAN DEFAULT '1'  NOT NULL,
CONSTRAINT PK_SERVICES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_SERVICES_DISPLAYEDNAME UNIQUE (DISPLAYEDNAME),
CONSTRAINT UQ_SERVICES_PRINTEDNAME UNIQUE (PRINTEDNAME)
);

CREATE SEQUENCE SEQ_SERVICES_ID;

 SET TERM !! ;
 CREATE TRIGGER TR_SERVICES_AUTOID for SERVICES
 active before insert position 0
 as
 begin
 if ((new.ID is null) or (new.ID = 0)) then
 begin
 new.id = gen_id(SEQ_SERVICES_ID,1);
 end
 end!!
 SET TERM ; !!

 COMMIT;
