CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;


CREATE TABLE BILLINGS
(
ID INTEGER NOT NULL,
BILLINGSTYPE_ID INTEGER,
NBROOMS INT NOT NULL,
BOOKING_ID INTEGER,
BILLINGADDRESS_ID INTEGER NOT NULL,
NBADULTS INTEGER DEFAULT 0,
NBCHILDREN INTEGER DEFAULT 0,
ARRIVINGDATE DATE NOT NULL,
DEPARTUREDATE DATE NOT NULL,
EXPECTEDDEPARTUREDATE DATE,
ISCLOSED BOOLEAN DEFAULT '0' NOT NULL,
NOTE VARCHAR(255),
CONSTRAINT PK_BILLINGS_ID PRIMARY KEY (ID),
CONSTRAINT CK_POS_BILLINGS_NBADULTS CHECK (NBADULTS >= 0),
CONSTRAINT CK_GREA_BILLINGS_EXDEPARRDATE CHECK (EXPECTEDDEPARTUREDATE >= ARRIVINGDATE),
CONSTRAINT CK_GREA_BILLINGS_DEPARRDATE CHECK (DEPARTUREDATE >= ARRIVINGDATE)
);

CREATE SEQUENCE SEQ_BILLINGS_ID;

 SET TERM !! ;
 CREATE TRIGGER TR_BILLINGS_AUTOID for BILLINGS
 active before insert position 0
 as
 begin
 if ((new.ID is null) or (new.ID = 0)) then
 begin
 new.id = NEXT VALUE FOR SEQ_BILLINGS_ID;
 end
 end!!
 SET TERM ; !!

 COMMIT;
