CONNECT 'localhost:/home/tiff/Stage-IUT/app/hotel-precheck/src/PreCheck/Database/PreCheckDB.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;

CREATE TABLE SERVICESDETAILS
 (
 SERVICE_ID INTEGER NOT NULL,
 SERVICEFIELD_ID INTEGER NOT NULL,
 FIELDVALUE VARCHAR(255),
 CONSTRAINT PK_SERVICESDETAILS_ID PRIMARY KEY (SERVICE_ID, SERVICEFIELD_ID)
 );

 COMMIT;
