CONNECT 'localhost:/home/tiff/Stage-IUT/app/hotel-precheck/src/PreCheck/Database/PreCheckDB.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;


CREATE TABLE CHARGEDSERVICES
(
SERVICE_ID INTEGER NOT NULL,
BILL_ID INTEGER NOT NULL,
RECEPTIONIST_ID INTEGER NOT NULL,
INVOICINGDATE DATE NOT NULL,
QUANTITY INT NOT NULL,
CHARGEDUNITYPRICE FLOAT,
VAT_PERCENTAGE FLOAT,
ISPRINTED BOOLEAN DEFAULT '0' NOT NULL,
ISPAYED BOOLEAN DEFAULT '0' NOT NULL,
PAIEMENTDATE DATE,
CONSTRAINT PK_CHARGEDSERVICES_SERVICEBILL PRIMARY KEY (SERVICE_ID,BILL_ID)
);


CREATE TRIGGER TR_REGISTERCHARGING FOR CHARGEDSERVICES
ACTIVE BEFORE UPDATE position 0
AS
BEGIN
IF ((new.ISPAYED = '1') AND (old.ISPAYED != '1')) THEN
BEGIN
EXECUTE INCREMENTHOURLYCOUNTERBY(new.CHARGEDUNITYPRICE*(1+VAT_PERCENTAGE)*new.QUANTITY);
END
END!!
SET TERM ; !!


 COMMIT;
