CONNECT TO "PreCheckArchivesDB" AS archives-hotel USER 'precheck' USING 'hotel';

COMMIT;


CREATE TABLE CLIENTS
(
ID SERIAL,
NAME VARCHAR(35) NOT NULL,
PHONE VARCHAR(12),
EMAIL VARCHAR(50),
IDCARDSCAN VARCHAR(100),
NATIONALITY_ID INTEGER NOT NULL,
HOMEADDRESS_ID INTEGER,
ISCURRENT BOOLEAN DEFAULT '0' NOT NULL,
CONSTRAINT PK_CLIENTS_ID PRIMARY KEY (ID),
CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL),
CONSTRAINT CK_VAL_CLIENTS_EMAIL CHECK(EMAIL SIMILAR TO '[[[:ALNUM:]\._%\+\-]+@[[:ALNUM:]\.-]+\.[[:ALPHA:]]+]?'),
CONSTRAINT CK_VAL_CLIENTS_PHONE CHECK(PHONE SIMILAR TO '[[\+|00][[1-9]]{3}[[:DIGIT:]]{8}]?')
);

 COMMIT;
