CONNECT archives-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;


CREATE TABLE NATIONALITIES
(
ID SERIAL,
CODE VARCHAR(3) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
LABEL VARCHAR(50) NOT NULL,
CONSTRAINT PK_NATIONALITIES_ID PRIMARY KEY (ID),
CONSTRAINT UQ_NATIONALITIES_CODE UNIQUE (CODE),
CONSTRAINT UQ_NATIONALITIES_LABEL UNIQUE (LABEL)
);

 COMMIT;
