CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;


CREATE TABLE USERS
(
ID INTEGER NOT NULL,
LOGIN VARCHAR(20) NOT NULL,
ENCRYPTEDPASS VARCHAR(255) NOT NULL,
ISRECEPTIONIST BOOLEAN DEFAULT '0' NOT NULL,
ISMANAGERX BOOLEAN DEFAULT '0' NOT NULL,
ISMANAGERZ BOOLEAN DEFAULT '0' NOT NULL,
ISADMINISTRATOR BOOLEAN DEFAULT '0' NOT NULL,
CONSTRAINT PK_USERS_ID PRIMARY KEY (ID),
CONSTRAINT UQ_USERS_LOGIN UNIQUE (LOGIN)
);

CREATE SEQUENCE SEQ_USERS_ID;

 SET TERM !! ;
 CREATE TRIGGER TR_USERS_AUTOID for USERS
 active before insert position 0
 as
 begin
 if ((new.ID is null) or (new.ID = 0)) then
 begin
 new.id = NEXT VALUE FOR SEQ_USERS_ID;
 end
 end!!
 SET TERM ; !!

 COMMIT;
