CONNECT TO "PreCheckDB" AS precheck-hotel USER 'precheck' USING 'hotel';

COMMIT;

CREATE TABLE ROOMS
(
ID SERIAL,
ROOMTYPE_ID INTEGER NOT NULL,
NUMBER SMALLINT NOT NULL,
FLOOR SMALLINT NOT NULL,
ISCLEANED BOOLEAN DEFAULT '1' NOT NULL,
CONSTRAINT PK_ROOMS_ID PRIMARY KEY (ID),
CONSTRAINT UQ_ROOMS_NUMBER UNIQUE (NUMBER)
);

 COMMIT;
