CONNECT TO "PreCheckDB" AS precheck-hotel USER 'precheck' USING 'hotel';

COMMIT;


CREATE TABLE BILLINGSCLIENTS
(
ID SERIAL,
CLIENT_ID INTEGER NOT NULL,
BILLING_ID INTEGER,
CONSTRAINT PK_BILLINGSCLIENTS_ID PRIMARY KEY (ID)
);

COMMIT;
