CONNECT precheck-hotel USER 'precheck' PASSWORD 'hotel';

COMMIT;

CREATE TABLE ROOMSOCCUPATIONS
(
ID INTEGER NOT NULL,
ROOM_ID INTEGER NOT NULL,
BILLING_ID INTEGER NOT NULL,
ARRIVINGDATE DATE NOT NULL,
DEPARTUREDATE DATE NOT NULL,
CONSTRAINT PK_ROOMSOCC_ROOMBILLING PRIMARY KEY (ROOM_ID, BILLING_ID),
CONSTRAINT UQ_ROOMSOCC_ROOMARRIVINGDATE UNIQUE (ROOM_ID, ARRIVINGDATE),
CONSTRAINT UQ_ROOMSOCC_ROOMDEPARTUREDATE UNIQUE (ROOM_ID, DEPARTUREDATE)
);
