CONNECT 'localhost:/home/tiff/Stage-IUT/app/hotel-precheck/src/PreCheck/Database/PreCheckDB.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

COMMIT;


SET TERM !! ;
CREATE PROCEDURE RESTARTYEARLYBALANCE (RESTARTYEAR AS INT)
AS
DECLARE VARIABLE NOWTIMESTAMP = CURRENT_TIMESTAMP;
DECLARE VARIABLE OLDBALANCE DOUBLE DEFAULT = 0.0;
DECLARE VARIABLE CURRENTBALANCE DOUBLE DEFAULT = 0.0;
BEGIN
SELECT BALANCE FROM YEARLYBALANCECOUNTER WHERE YEARLOG = (:RESTARTYEAR-1) INTO :OLDBALANCE;
IF :OLDBALANCE IS NULL THEN
	OLDBALANCE = 0.0;
END IF;
SELECT BALANCE FROM BALANCELOG WHERE YEARLOG = (:RESTARTYEAR-1) INTO :CURRENTBALANCE;
IF :CURRENTBALANCE IS NOT NULL THEN
	UPDATE BALANCELOG SET BALANCE = (:OLDBALANCE + :CURRENTBALANCE) WHERE YEARLOG =(:RESTARTYEAR-1);
ELSE
INSERT INTO BALANCELOG(YEARLOG, MONTHLOG, DAYLOG, HOURLOG, BALANCE) VALUES ((:RESTARTYEAR-1), 0, 0, 0, :OLDBALANCE);
END IF;
-- create new counter (ràz)
INSERT INTO YEARLYBALANCECOUNTER(CREATIONTIME, YEARLOG, BALANCE) VALUES (:NOWTIMESTAMP, :RESTARTYEAR, 0);
END!!

CREATE PROCEDURE RESTARTMONTHLYBALANCE (RESTARTYEAR AS INT, RESTARTMONTH AS INT)
AS
DECLARE VARIABLE NOWTIMESTAMP = CURRENT_TIMESTAMP;
DECLARE VARIABLE OLDBALANCE DOUBLE DEFAULT = 0.0;
DECLARE VARIABLE CURRENTBALANCE DOUBLE DEFAULT = 0.0;
DECLARE VARIABLE PREVIOUSYEAR INT;
BEGIN
IF :RESTARTMONTH = 1 THEN
:PREVIOUSYEAR = :RESTARTYEAR-1;
ELSE
:PREVIOUSYEAR = :RESTARTYEAR;
END IF;
SELECT BALANCE FROM MONTHLYBALANCECOUNTER WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = (:RESTARTMONTH-1) INTO :OLDBALANCE;
IF :OLDBALANCE IS NULL THEN
	OLDBALANCE = 0.0;
END IF;
SELECT BALANCE FROM BALANCELOG WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = (:RESTARTMONTH-1) INTO :CURRENTBALANCE;
IF :CURRENTBALANCE IS NOT NULL THEN
	UPDATE BALANCELOG SET BALANCE = (:OLDBALANCE + :CURRENTBALANCE) WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = (:RESTARTMONTH-1);
ELSE
INSERT INTO BALANCELOG(YEARLOG, MONTHLOG, DAYLOG, HOURLOG, BALANCE) VALUES (:PREVIOUSYEAR, (:RESTARTMONTH-1), 0, 0, :OLDBALANCE);
END IF;
-- create new counter (ràz)
INSERT INTO MONTHLYBALANCECOUNTER(CREATIONTIME, YEARLOG, MONTHLOG, BALANCE) VALUES (:NOWTIMESTAMP, :RESTARTYEAR, :RESTARTMONTH, 0);
END!!



CREATE PROCEDURE RESTARTDAILYBALANCE (RESTARTYEAR AS INT, RESTARTMONTH AS INT, RESTARTDAY AS INT)
AS
DECLARE VARIABLE NOWTIMESTAMP = CURRENT_TIMESTAMP;
DECLARE VARIABLE OLDBALANCE DOUBLE DEFAULT = 0.0;
DECLARE VARIABLE CURRENTBALANCE DOUBLE DEFAULT = 0.0;
DECLARE VARIABLE PREVIOUSYEAR INT;
DECLARE VARIABLE PREVIOUSMONTH INT;
BEGIN
IF :RESTARTMONTH = 1 THEN
:PREVIOUSYEAR = :RESTARTYEAR-1;
ELSE
:PREVIOUSYEAR = :RESTARTYEAR;
END IF;
IF :RESTARTDAY = 1 THEN
:PREVIOUSMONTH = :RESTARTMONTH-1;
ELSE
:PREVIOUSMONTH = :RESTARTMONTH;
END IF;
SELECT BALANCE FROM DAYBALANCECOUNTER WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = :PREVIOUSMONTH AND DAYLOG = (:RESTARTDAY-1) INTO :OLDBALANCE;
IF :OLDBALANCE IS NULL THEN
	OLDBALANCE = 0.0;
END IF;
SELECT BALANCE FROM BALANCELOG WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = :PREVIOUSMONTH AND DAYLOG = (:RESTARTDAY-1) INTO :CURRENTBALANCE;
IF :CURRENTBALANCE IS NOT NULL THEN
	UPDATE BALANCELOG SET BALANCE = (:OLDBALANCE + :CURRENTBALANCE) WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = :PREVIOUSMONTH AND DAYLOG = (:RESTARTDAY-1);
ELSE
INSERT INTO BALANCELOG(YEARLOG, MONTHLOG, DAYLOG, HOURLOG, BALANCE) VALUES (:PREVIOUSYEAR, :PREVIOUSMONTH, (:RESTARTDAY-1), 0, :OLDBALANCE);
END IF;
-- create new counter (ràz)
INSERT INTO DAYLYBALANCECOUNTER(CREATIONTIME, YEARLOG, MONTHLOG, DAYLOG, BALANCE) VALUES (:NOWTIMESTAMP, :RESTARTYEAR, :RESTARTMONTH, :RESTARTDAY, 0);
END!!


CREATE PROCEDURE RESTARTHOURLYBALANCE (RESTARTYEAR AS INT, RESTARTMONTH AS INT, RESTARTDAY AS INT, RESTARTHOUR AS INT)
AS
DECLARE VARIABLE NOWTIMESTAMP = CURRENT_TIMESTAMP;
DECLARE VARIABLE OLDBALANCE DOUBLE DEFAULT = 0.0;
DECLARE VARIABLE CURRENTBALANCE DOUBLE DEFAULT = 0.0;
DECLARE VARIABLE PREVIOUSYEAR INT;
DECLARE VARIABLE PREVIOUSMONTH INT;
DECLARE VARIABLE PREVIOUSDAY INT;
BEGIN
IF :RESTARTMONTH = 1 THEN
:PREVIOUSYEAR = :RESTARTYEAR-1;
ELSE
:PREVIOUSYEAR = :RESTARTYEAR;
END IF;
IF :RESTARTDAY = 1 THEN
:PREVIOUSMONTH = :RESTARTMONTH-1;
ELSE
:PREVIOUSMONTH = :RESTARTMONTH;
END IF;
IF :RESTARTHOUR = 1 THEN
:PREVIOUSDAY = :PREVIOUSDAY-1;
ELSE
:PREVIOUSDAY = :PREVIOUSDAY;
END IF;
SELECT BALANCE FROM HOURLYBALANCECOUNTER WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = :PREVIOUSMONTH AND DAYLOG = (:RESTARTDAY-1) INTO :OLDBALANCE;
IF :OLDBALANCE IS NULL THEN
	OLDBALANCE = 0.0;
END IF;
SELECT BALANCE FROM BALANCELOG WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = :PREVIOUSMONTH AND DAYLOG = :PREVIOUSDAY AND HOURLOG = (:RESTARTHOUR-1) INTO :CURRENTBALANCE;
IF :CURRENTBALANCE IS NOT NULL THEN
BEGIN
	UPDATE BALANCELOG SET BALANCE = (:OLDBALANCE + :CURRENTBALANCE) WHERE YEARLOG = :PREVIOUSYEAR AND MONTHLOG = :PREVIOUSMONTH AND DAYLOG = :PREVIOUSDAY AND HOURLOG = (:RESTARTHOUR-1);
END
ELSE
BEGIN
INSERT INTO BALANCELOG(YEARLOG, MONTHLOG, DAYLOG, HOURLOG, BALANCE) VALUES (:PREVIOUSYEAR, :PREVIOUSMONTH, :PREVIOUSDAY, (:RESTARTHOUR-1), :OLDBALANCE);
END
-- create new counter (ràz)
INSERT INTO HOURLYBALANCECOUNTER(CREATIONTIME, YEARLOG, MONTHLOG, DAYLOG, HOURLOG, BALANCE) VALUES (:NOWTIMESTAMP, :RESTARTYEAR, :RESTARTMONTH, :RESTARTDAY, :RESTARTHOUR, 0;
END!!


CREATE PROCEDURE INCREMENTHOURLYCOUNTERBY (SUPPLEMENT AS DOUBLE)
AS
BEGIN
UPDATE HOURLYBALANCECOUNTER SET BALANCE = BALANCE+:SUPPLEMENT WHERE CREATIONTIME >= MAX(CREATIONTIME);
END!!


CREATE PROCEDURE INCREMENTDAYLYCOUNTERBY (SUPPLEMENT AS DOUBLE)
AS
BEGIN
UPDATE DAYLYBALANCECOUNTER SET BALANCE = BALANCE+:SUPPLEMENT WHERE CREATIONTIME >= MAX(CREATIONTIME);
END!!


CREATE PROCEDURE INCREMENTMONTHLYCOUNTERBY (SUPPLEMENT AS DOUBLE)
AS
BEGIN
UPDATE MONTHLYBALANCECOUNTER SET BALANCE = BALANCE+:SUPPLEMENT WHERE CREATIONTIME >= MAX(CREATIONTIME);
END!!


CREATE PROCEDURE INCREMENTYEARLYCOUNTERBY (SUPPLEMENT AS DOUBLE)
AS
BEGIN
UPDATE YEARLYBALANCECOUNTER SET BALANCE = BALANCE+:SUPPLEMENT WHERE CREATIONTIME >= MAX(CREATIONTIME);
END!!

SET TERM ; !!

 
COMMIT;
