.TH "Répertoire de référence de views" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de views \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBqml\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBSH_ExtendedQQmlAction\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBSH_ExtendedQQmlAction\&.h\fP"
.br
.in -1c
