.TH "SH_DatabaseManager.cpp" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_DatabaseManager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SH_DatabaseManager\&.h'\fP
.br
\fC#include 'SH_MessageManager\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QtSql>\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
