.TH "SH_TabZone" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_TabZone \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBTabView\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBnewBilling\fP ()"
.br
.ti -1c
.RI "void \fBnewBooking\fP ()"
.br
.ti -1c
.RI "void \fBnewSelling\fP ()"
.br
.ti -1c
.RI "void \fBreload\fP ()"
.br
.ti -1c
.RI "void \fBselected\fP (string selectedItem)"
.br
.ti -1c
.RI "void \fBselectedForDetail\fP (var data)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBopenTab\fP (tabIndex)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "var \fBstdKeyboard\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_TabZone\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_TabZone::newBilling ()\fC [signal]\fP"

.SS "void SH_TabZone::newBooking ()\fC [signal]\fP"

.SS "void SH_TabZone::newSelling ()\fC [signal]\fP"

.SS "void SH_TabZone::openTab (tabIndex)"

.SS "void SH_TabZone::reload ()\fC [signal]\fP"

.SS "void SH_TabZone::selected (stringselectedItem)\fC [signal]\fP"

.SS "void SH_TabZone::selectedForDetail (vardata)\fC [signal]\fP"

.SH "Documentation des propriétés"
.PP 
.SS "var SH_TabZone::stdKeyboard"

.PP
Définition à la ligne 7 du fichier SH_TabZone\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
