.TH "models/SH_User.cpp" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models/SH_User.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QSqlRecord>\fP
.br
\fC#include <QtCore>\fP
.br
\fC#include <QCryptographicHash>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'SH_User\&.h'\fP
.br
\fC#include 'SH_Trainee\&.h'\fP
.br
\fC#include 'SH_DatabaseManager\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
