.TH "ComplexColumn" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComplexColumn \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBColumn\fP\&.
.SS "Propriétés"

.in +1c
.ti -1c
.RI "real \fBinnerHeight\fP"
.br
.ti -1c
.RI "real \fBinnerWidth\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1 du fichier ComplexColumn\&.qml\&.
.SH "Documentation des propriétés"
.PP 
.SS "real ComplexColumn::innerHeight"

.PP
Définition à la ligne 4 du fichier ComplexColumn\&.qml\&.
.SS "real ComplexColumn::innerWidth"

.PP
Définition à la ligne 6 du fichier ComplexColumn\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
