.TH "logging/QsLogDest.h" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging/QsLogDest.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'QsLogLevel\&.h'\fP
.br
\fC#include <QSharedPointer>\fP
.br
\fC#include <QtGlobal>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQsLogging::Destination\fP"
.br
.RI "\fIThe \fBDestination\fP class\&. \fP"
.ti -1c
.RI "class \fBQsLogging::DestinationFactory\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBQsLogging\fP"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef QSharedPointer
.br
< Destination > \fBQsLogging::DestinationPtr\fP"
.br
.RI "\fIDestinationPtr\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
