.TH "logging/QsLogDest.cpp" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging/QsLogDest.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'QsLogDest\&.h'\fP
.br
\fC#include 'QsLogDestConsole\&.h'\fP
.br
\fC#include 'QsLogDestFile\&.h'\fP
.br
\fC#include <QString>\fP
.br

.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBQsLogging\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
