.TH "logging/QsLog.h" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging/QsLog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'QsLogLevel\&.h'\fP
.br
\fC#include 'QsLogDest\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QString>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQsLogging::Logger\fP"
.br
.ti -1c
.RI "class \fBQsLogging::Logger::Helper\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBQsLogging\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQLOG_DEBUG\fP()"
.br
.ti -1c
.RI "#define \fBQLOG_ERROR\fP()"
.br
.ti -1c
.RI "#define \fBQLOG_FATAL\fP()"
.br
.ti -1c
.RI "#define \fBQLOG_INFO\fP()"
.br
.ti -1c
.RI "#define \fBQLOG_TRACE\fP()"
.br
.ti -1c
.RI "#define \fBQLOG_WARN\fP()"
.br
.ti -1c
.RI "#define \fBQS_LOG_VERSION\fP   '2\&.0b1'"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define QLOG_DEBUG()"
\fBValeur :\fP
.PP
.nf
if (QsLogging::Logger::instance()\&.loggingLevel() > QsLogging::DebugLevel) {} \
    else QsLogging::Logger::Helper(QsLogging::DebugLevel)\&.stream()
.fi
.PP
Définition à la ligne 221 du fichier QsLog\&.h\&.
.SS "#define QLOG_ERROR()"
\fBValeur :\fP
.PP
.nf
if (QsLogging::Logger::instance()\&.loggingLevel() > QsLogging::ErrorLevel) {} \
    else QsLogging::Logger::Helper(QsLogging::ErrorLevel)\&.stream()
.fi
.PP
Définition à la ligne 230 du fichier QsLog\&.h\&.
.SS "#define QLOG_FATAL()"
\fBValeur :\fP
.PP
.nf
if (QsLogging::Logger::instance()\&.loggingLevel() > QsLogging::FatalLevel) {} \
    else QsLogging::Logger::Helper(QsLogging::FatalLevel)\&.stream()
.fi
.PP
Définition à la ligne 233 du fichier QsLog\&.h\&.
.SS "#define QLOG_INFO()"
\fBValeur :\fP
.PP
.nf
if (QsLogging::Logger::instance()\&.loggingLevel() > QsLogging::InfoLevel) {} \
    else QsLogging::Logger::Helper(QsLogging::InfoLevel)\&.stream()
.fi
.PP
Définition à la ligne 224 du fichier QsLog\&.h\&.
.PP
Référencé par main()\&.
.SS "#define QLOG_TRACE()"
\fBValeur :\fP
.PP
.nf
if (QsLogging::Logger::instance()\&.loggingLevel() > QsLogging::TraceLevel) {} \
    else QsLogging::Logger::Helper(QsLogging::TraceLevel)\&.stream()
.fi
.PP
Définition à la ligne 218 du fichier QsLog\&.h\&.
.SS "#define QLOG_WARN()"
\fBValeur :\fP
.PP
.nf
if (QsLogging::Logger::instance()\&.loggingLevel() > QsLogging::WarnLevel) {} \
    else QsLogging::Logger::Helper(QsLogging::WarnLevel)\&.stream()
.fi
.PP
Définition à la ligne 227 du fichier QsLog\&.h\&.
.SS "#define QS_LOG_VERSION   '2\&.0b1'"

.PP
Définition à la ligne 55 du fichier QsLog\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
