.TH "logging/QsLogDestFile.h" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging/QsLogDestFile.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'QsLogDest\&.h'\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QtGlobal>\fP
.br
\fC#include <QSharedPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQsLogging::FileDestination\fP"
.br
.RI "\fIThe \fBFileDestination\fP class\&. \fP"
.ti -1c
.RI "class \fBQsLogging::NullRotationStrategy\fP"
.br
.RI "\fIThe \fBNullRotationStrategy\fP class\&. \fP"
.ti -1c
.RI "class \fBQsLogging::RotationStrategy\fP"
.br
.RI "\fIThe \fBRotationStrategy\fP class\&. \fP"
.ti -1c
.RI "class \fBQsLogging::SizeRotationStrategy\fP"
.br
.RI "\fIThe \fBSizeRotationStrategy\fP class\&. \fP"
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBQsLogging\fP"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef QSharedPointer
.br
< RotationStrategy > \fBQsLogging::RotationStrategyPtr\fP"
.br
.RI "\fIRotationStrategyPtr\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
