.TH "QsLogging::DebugOutputDestination" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QsLogging::DebugOutputDestination \- 
.PP
The \fBDebugOutputDestination\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QsLogDestConsole\&.h>\fP
.PP
Est dérivée de \fBQsLogging::Destination\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "virtual bool \fBisValid\fP ()"
.br
.RI "\fIisValid \fP"
.ti -1c
.RI "virtual void \fBwrite\fP (const QString &message, \fBLevel\fP level)"
.br
.RI "\fIwrite \fP"
.in -1c
.SH "Description détaillée"
.PP 
The \fBDebugOutputDestination\fP class\&. 
.PP
Définition à la ligne 74 du fichier QsLogDestConsole\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "bool QsLogging::DebugOutputDestination::isValid ()\fC [virtual]\fP"

.PP
isValid 
.PP
\fBRenvoie:\fP
.RS 4

.RE
.PP

.PP
Implémente \fBQsLogging::Destination\fP\&.
.PP
Définition à la ligne 104 du fichier QsLogDestConsole\&.cpp\&.
.PP
.nf
105 {
106     return true;
107 }
.fi
.SS "void QsLogging::DebugOutputDestination::write (const QString &message, \fBLevel\fPlevel)\fC [virtual]\fP"

.PP
write 
.PP
\fBParamètres:\fP
.RS 4
\fImessage\fP 
.br
\fIlevel\fP \fBQsLogging::DebugOutputDestination::write\fP 
.RE
.PP

.PP
Implémente \fBQsLogging::Destination\fP\&.
.PP
Définition à la ligne 99 du fichier QsLogDestConsole\&.cpp\&.
.PP
Références QsDebugOutput::output()\&.
.PP
.nf
100 {
101     QsDebugOutput::output(message);
102 }
.fi


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
