.TH "QsLogging::RotationStrategy" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QsLogging::RotationStrategy \- 
.PP
The \fBRotationStrategy\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QsLogDestFile\&.h>\fP
.PP
Dérivée par \fBQsLogging::NullRotationStrategy\fP, et \fBQsLogging::SizeRotationStrategy\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "virtual \fB~RotationStrategy\fP ()"
.br
.RI "\fI~RotationStrategy \fP"
.ti -1c
.RI "virtual void \fBincludeMessageInCalculation\fP (const QString &message)=0"
.br
.RI "\fIincludeMessageInCalculation \fP"
.ti -1c
.RI "virtual QIODevice::OpenMode \fBrecommendedOpenModeFlag\fP ()=0"
.br
.RI "\fIrecommendedOpenModeFlag \fP"
.ti -1c
.RI "virtual void \fBrotate\fP ()=0"
.br
.RI "\fIrotate \fP"
.ti -1c
.RI "virtual void \fBsetInitialInfo\fP (const QFile &file)=0"
.br
.RI "\fIsetInitialInfo \fP"
.ti -1c
.RI "virtual bool \fBshouldRotate\fP ()=0"
.br
.RI "\fIshouldRotate \fP"
.in -1c
.SH "Description détaillée"
.PP 
The \fBRotationStrategy\fP class\&. 
.PP
Définition à la ligne 40 du fichier QsLogDestFile\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "QsLogging::RotationStrategy::~RotationStrategy ()\fC [virtual]\fP"

.PP
~RotationStrategy \fBQsLogging::RotationStrategy::~RotationStrategy\fP 
.PP
Définition à la ligne 38 du fichier QsLogDestFile\&.cpp\&.
.PP
.nf
39 {
40 }
.fi
.SH "Documentation des fonctions membres"
.PP 
.SS "virtual void QsLogging::RotationStrategy::includeMessageInCalculation (const QString &message)\fC [pure virtual]\fP"

.PP
includeMessageInCalculation 
.PP
\fBParamètres:\fP
.RS 4
\fImessage\fP 
.RE
.PP

.PP
Implémenté dans \fBQsLogging::SizeRotationStrategy\fP, et \fBQsLogging::NullRotationStrategy\fP\&.
.SS "virtual QIODevice::OpenMode QsLogging::RotationStrategy::recommendedOpenModeFlag ()\fC [pure virtual]\fP"

.PP
recommendedOpenModeFlag 
.PP
\fBRenvoie:\fP
.RS 4

.RE
.PP

.PP
Implémenté dans \fBQsLogging::SizeRotationStrategy\fP, et \fBQsLogging::NullRotationStrategy\fP\&.
.SS "virtual void QsLogging::RotationStrategy::rotate ()\fC [pure virtual]\fP"

.PP
rotate 
.PP
Implémenté dans \fBQsLogging::SizeRotationStrategy\fP, et \fBQsLogging::NullRotationStrategy\fP\&.
.SS "virtual void QsLogging::RotationStrategy::setInitialInfo (const QFile &file)\fC [pure virtual]\fP"

.PP
setInitialInfo 
.PP
\fBParamètres:\fP
.RS 4
\fIfile\fP 
.RE
.PP

.PP
Implémenté dans \fBQsLogging::SizeRotationStrategy\fP, et \fBQsLogging::NullRotationStrategy\fP\&.
.SS "virtual bool QsLogging::RotationStrategy::shouldRotate ()\fC [pure virtual]\fP"

.PP
shouldRotate 
.PP
\fBRenvoie:\fP
.RS 4

.RE
.PP

.PP
Implémenté dans \fBQsLogging::SizeRotationStrategy\fP, et \fBQsLogging::NullRotationStrategy\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
