.TH "logging/QsLogDisableForThisFile.h" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging/QsLogDisableForThisFile.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtDebug>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQLOG_DEBUG\fP()   if (1) {} else qDebug()"
.br
.ti -1c
.RI "#define \fBQLOG_ERROR\fP()   if (1) {} else qDebug()"
.br
.ti -1c
.RI "#define \fBQLOG_FATAL\fP()   if (1) {} else qDebug()"
.br
.ti -1c
.RI "#define \fBQLOG_INFO\fP()   if (1) {} else qDebug()"
.br
.ti -1c
.RI "#define \fBQLOG_TRACE\fP()   if (1) {} else qDebug()"
.br
.ti -1c
.RI "#define \fBQLOG_WARN\fP()   if (1) {} else qDebug()"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define QLOG_DEBUG()   if (1) {} else qDebug()"

.PP
Définition à la ligne 16 du fichier QsLogDisableForThisFile\&.h\&.
.SS "#define QLOG_ERROR()   if (1) {} else qDebug()"

.PP
Définition à la ligne 19 du fichier QsLogDisableForThisFile\&.h\&.
.SS "#define QLOG_FATAL()   if (1) {} else qDebug()"

.PP
Définition à la ligne 20 du fichier QsLogDisableForThisFile\&.h\&.
.SS "#define QLOG_INFO()   if (1) {} else qDebug()"

.PP
Définition à la ligne 17 du fichier QsLogDisableForThisFile\&.h\&.
.SS "#define QLOG_TRACE()   if (1) {} else qDebug()"

.PP
Définition à la ligne 15 du fichier QsLogDisableForThisFile\&.h\&.
.SS "#define QLOG_WARN()   if (1) {} else qDebug()"

.PP
Définition à la ligne 18 du fichier QsLogDisableForThisFile\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
