.TH "logging/QsLogLevel.h" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging/QsLogLevel.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "\fBQsLogging\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBQsLogging::Level\fP { \fBQsLogging::TraceLevel\fP = 0, \fBQsLogging::DebugLevel\fP, \fBQsLogging::InfoLevel\fP, \fBQsLogging::WarnLevel\fP, \fBQsLogging::ErrorLevel\fP, \fBQsLogging::FatalLevel\fP, \fBQsLogging::OffLevel\fP }"
.br
.RI "\fIThe Level enum\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
