.TH "QsLogging::DestinationFactory" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QsLogging::DestinationFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QsLogDest\&.h>\fP
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBDestinationPtr\fP \fBMakeDebugOutputDestination\fP ()"
.br
.RI "\fIMakeDebugOutputDestination\&. \fP"
.ti -1c
.RI "static \fBDestinationPtr\fP \fBMakeFileDestination\fP (const QString &filePath, bool enableRotation=false, qint64 sizeInBytesToRotateAfter=0, int oldLogsToKeep=0)"
.br
.RI "\fIMakeFileDestination\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 89 du fichier QsLogDest\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBDestinationPtr\fP QsLogging::DestinationFactory::MakeDebugOutputDestination ()\fC [static]\fP"

.PP
MakeDebugOutputDestination\&. 
.PP
\fBRenvoie:\fP
.RS 4

.RE
.PP
\fBDestinationFactory::MakeDebugOutputDestination\fP 
.PP
Définition à la ligne 76 du fichier QsLogDest\&.cpp\&.
.PP
Référencé par enableLogging()\&.
.PP
.nf
77 {
78     return DestinationPtr(new DebugOutputDestination);
79 }
.fi
.SS "\fBDestinationPtr\fP QsLogging::DestinationFactory::MakeFileDestination (const QString &filePath, boolenableRotation = \fCfalse\fP, qint64sizeInBytesToRotateAfter = \fC0\fP, intoldLogsToKeep = \fC0\fP)\fC [static]\fP"

.PP
MakeFileDestination\&. destination factory
.PP
\fBParamètres:\fP
.RS 4
\fIfilePath\fP 
.br
\fIenableRotation\fP 
.br
\fIsizeInBytesToRotateAfter\fP 
.br
\fIoldLogsToKeep\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
.RE
.PP
\fBDestinationFactory::MakeFileDestination\fP 
.PP
Définition à la ligne 60 du fichier QsLogDest\&.cpp\&.
.PP
Référencé par enableLogging()\&.
.PP
.nf
62 {
63     if (enableRotation) {
64         QScopedPointer<SizeRotationStrategy> logRotation(new SizeRotationStrategy);
65         logRotation->setMaximumSizeInBytes(sizeInBytesToRotateAfter);
66         logRotation->setBackupCount(oldLogsToKeep);
67 
68         return DestinationPtr(new FileDestination(filePath, RotationStrategyPtr(logRotation\&.take())));
69     }
70 
71     return DestinationPtr(new FileDestination(filePath, RotationStrategyPtr(new NullRotationStrategy)));
72 }
.fi


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
