.TH "SH_CalendarDialog" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_CalendarDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBRectangle\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBclicked\fP (date selectedDate)"
.br
.ti -1c
.RI "void \fBclosed\fP ()"
.br
.ti -1c
.RI "void \fBopened\fP ()"
.br
.ti -1c
.RI "void \fBrefresh\fP (date newDate)"
.br
.ti -1c
.RI "void \fBselected\fP (string selectedDate)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "alias \fBcurrentDate\fP"
.br
.ti -1c
.RI "alias \fBcurrentDay\fP"
.br
.ti -1c
.RI "alias \fBcurrentMonth\fP"
.br
.ti -1c
.RI "alias \fBcurrentMonthLength\fP"
.br
.ti -1c
.RI "alias \fBcurrentWeekday\fP"
.br
.ti -1c
.RI "alias \fBcurrentYear\fP"
.br
.ti -1c
.RI "int \fBfirstWeekdayIndex\fP"
.br
.ti -1c
.RI "variant \fBmonthsList\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "variant \fBweekdaysList\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_CalendarDialog\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_CalendarDialog::clicked (dateselectedDate)\fC [signal]\fP"

.SS "void SH_CalendarDialog::closed ()\fC [signal]\fP"

.SS "void SH_CalendarDialog::opened ()\fC [signal]\fP"

.SS "void SH_CalendarDialog::refresh (datenewDate)\fC [signal]\fP"

.SS "void SH_CalendarDialog::selected (stringselectedDate)\fC [signal]\fP"

.SH "Documentation des propriétés"
.PP 
.SS "alias SH_CalendarDialog::currentDate"

.PP
Définition à la ligne 11 du fichier SH_CalendarDialog\&.qml\&.
.SS "alias SH_CalendarDialog::currentDay"

.PP
Définition à la ligne 15 du fichier SH_CalendarDialog\&.qml\&.
.SS "alias SH_CalendarDialog::currentMonth"

.PP
Définition à la ligne 17 du fichier SH_CalendarDialog\&.qml\&.
.SS "alias SH_CalendarDialog::currentMonthLength"

.PP
Définition à la ligne 21 du fichier SH_CalendarDialog\&.qml\&.
.SS "alias SH_CalendarDialog::currentWeekday"

.PP
Définition à la ligne 13 du fichier SH_CalendarDialog\&.qml\&.
.SS "alias SH_CalendarDialog::currentYear"

.PP
Définition à la ligne 19 du fichier SH_CalendarDialog\&.qml\&.
.SS "int SH_CalendarDialog::firstWeekdayIndex"

.PP
Définition à la ligne 7 du fichier SH_CalendarDialog\&.qml\&.
.SS "variant SH_CalendarDialog::monthsList"

.PP
Définition à la ligne 23 du fichier SH_CalendarDialog\&.qml\&.
.SS "string SH_CalendarDialog::text"

.PP
Définition à la ligne 9 du fichier SH_CalendarDialog\&.qml\&.
.SS "variant SH_CalendarDialog::weekdaysList"

.PP
Définition à la ligne 25 du fichier SH_CalendarDialog\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
