.TH "SH_SqlDataView" 3 "Jeudi Juin 20 2013" "Version 0.3" "PreCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SH_SqlDataView \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBRectangle\fP\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBnewItem\fP ()"
.br
.ti -1c
.RI "void \fBselected\fP (string selectedItem)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "string \fBemptyDelegate\fP"
.br
.ti -1c
.RI "bool \fBfilterIndicatorsVisibles\fP"
.br
.ti -1c
.RI "string \fBfiltersTitle\fP"
.br
.ti -1c
.RI "bool \fBisEmpty\fP"
.br
.ti -1c
.RI "string \fBitemDelegate\fP"
.br
.ti -1c
.RI "string \fBsectionDelegate\fP"
.br
.ti -1c
.RI "var \fBsqlModel\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier SH_SqlDataView\&.qml\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void SH_SqlDataView::newItem ()\fC [signal]\fP"

.SS "void SH_SqlDataView::selected (stringselectedItem)\fC [signal]\fP"

.SH "Documentation des propriétés"
.PP 
.SS "string SH_SqlDataView::emptyDelegate"

.PP
Définition à la ligne 11 du fichier SH_SqlDataView\&.qml\&.
.SS "bool SH_SqlDataView::filterIndicatorsVisibles"
type: bool visibilité des cases à cocher permettant le tri du modèle 
.PP
Définition à la ligne 17 du fichier SH_SqlDataView\&.qml\&.
.SS "string SH_SqlDataView::filtersTitle"

.PP
Définition à la ligne 19 du fichier SH_SqlDataView\&.qml\&.
.SS "bool SH_SqlDataView::isEmpty"

.PP
Définition à la ligne 21 du fichier SH_SqlDataView\&.qml\&.
.SS "string SH_SqlDataView::itemDelegate"

.PP
Définition à la ligne 9 du fichier SH_SqlDataView\&.qml\&.
.SS "string SH_SqlDataView::sectionDelegate"

.PP
Définition à la ligne 13 du fichier SH_SqlDataView\&.qml\&.
.SS "var SH_SqlDataView::sqlModel"

.PP
Définition à la ligne 7 du fichier SH_SqlDataView\&.qml\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour PreCheck à partir du code source\&.
